-- Import restaurací PRAHA 1–100 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10
  (
    'la-degustation-boheme-bourgeoise',
    'La Degustation Bohême Bourgeoise',
    'Praha 1',
    '🍷 LUXE',
    'fine dining / michelinská',
    'Michelinská restaurace s moderní českou kuchyní, nejvyšší úroveň.',
    50.0879,
    14.4197,
    'https://www.ladegustation.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'field-restaurant',
    'Field Restaurant',
    'Praha 1',
    '🍷 LUXE',
    'fine dining / michelinská',
    'Michelinská hvězda, sezónní kuchyně s důrazem na lokální suroviny.',
    50.0891,
    14.4211,
    'https://www.fieldrestaurant.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-alcron',
    'Restaurace Alcron',
    'Praha 1',
    '🍷 LUXE',
    'fine dining / michelinská',
    'Legendární michelinská restaurace, česká i světová gastronomie.',
    50.0869,
    14.4284,
    'https://www.alcron.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kampa-park',
    'Kampa Park',
    'Praha 1',
    '🍷 LUXE',
    'fine dining / mezinárodní',
    'Ikonická restaurace u Karlova mostu, výhled na Vltavu.',
    50.0862,
    14.4098,
    'https://www.kampapark.com/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-fleků',
    'Restaurace U Fleků',
    'Praha 1',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Legendární pivovar od roku 1499, živá atmosféra.',
    50.0792,
    14.4189,
    'https://www.ufleku.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-zlatého-tygra',
    'U Zlatého tygra',
    'Praha 1',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Kultovní pražská hospoda, oblíbená Havlem a Clintonem.',
    50.0857,
    14.4167,
    'https://www.uzlatehotygra.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-parlamentu',
    'Restaurace U Parlamentu',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace v centru, spolehlivá klasika.',
    50.0875,
    14.4201,
    'https://www.uparlamentu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'lokál-dlouhááá',
    'Lokál Dlouhááá',
    'Praha 1',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Moderní pivnice s českou klasikou, čepované pivo.',
    50.0889,
    14.4235,
    'https://www.lokal-dlouha.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'café-savoy',
    'Café Savoy',
    'Praha 1',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Historická kavárna s vynikající snídaní a obědy.',
    50.0811,
    14.4067,
    'https://www.cafesavoy.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-bellevue',
    'Restaurace Bellevue',
    'Praha 1',
    '🍷 LUXE',
    'fine dining / moderní evropská',
    'Luxusní restaurace s výhledem na Karlův most.',
    50.0866,
    14.4132,
    'https://www.bellevuerestaurant.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20
  (
    'sansho',
    'Sansho',
    'Praha 5',
    '🍷 LUXE',
    'asijská fúze / fine dining',
    'Kreativní asijská kuchyně, autor Paul Day.',
    50.0721,
    14.4012,
    'https://www.sansho.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'eska',
    'Eska',
    'Praha 7',
    '🌿 PURE',
    'moderní česká / pekárna',
    'Moderní bistro s vlastní pekárnou, sezónní kuchyně.',
    50.0951,
    14.4389,
    'https://www.eska.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-v-zátiší',
    'Restaurace V Zátiší',
    'Praha 1',
    '🍷 LUXE',
    'fine dining / mezinárodní',
    'Jedna z nejlepších restaurací v Praze, vynikající gastronomie.',
    50.0881,
    14.4178,
    'https://www.vzatisi.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'aromi',
    'Aromi',
    'Praha 1',
    '🍷 LUXE',
    'italská / fine dining',
    'Autentická italská kuchyně, michelinská úroveň.',
    50.0863,
    14.4245,
    'https://www.aromi.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'lokál-u-bílé-kuželky',
    'Lokál U Bílé kuželky',
    'Praha 2',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbený Lokál na Vinohradech, čerstvé pivo.',
    50.0756,
    14.4398,
    'https://www.lokal-ubilekuzelky.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'maso-a-kobliha',
    'MASO A KOBLIHA',
    'Praha 7',
    '🔥 DRAMA',
    'burger / grill',
    'Nejlepší burgery v Praze, kultovní místo.',
    50.0989,
    14.4412,
    'https://www.masoakobliha.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'manifesto-market',
    'Manifesto Market',
    'Praha 7',
    '🌮 CHAOS',
    'street food / food market',
    'Food market s různými stánky, živá atmosféra.',
    50.0934,
    14.4456,
    'https://www.manifestomarket.com/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-černého-vola',
    'Restaurace U Černého vola',
    'Praha 1',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Autentická hospoda na Hradčanech, místní atmosféra.',
    50.0891,
    14.3912,
    'https://www.ucernehovala.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-terasa-u-zlaté-studně',
    'Restaurace Terasa U Zlaté studně',
    'Praha 1',
    '🍷 LUXE',
    'fine dining / vyhlídková',
    'Michelinská restaurace s nejlepším výhledem na Prahu.',
    50.0879,
    14.4023,
    'https://www.terraceuzlatestudne.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'naše-maso',
    'Naše maso',
    'Praha 2',
    '🔥 DRAMA',
    'steakhouse / řeznictví',
    'Kvalitní maso přímo od řezníka, steaky a burgery.',
    50.0778,
    14.4421,
    'https://www.nasemaso.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-30
  (
    'restaurace-hergetova-cihelna',
    'Restaurace Hergetova cihelna',
    'Praha 1',
    '🍷 LUXE',
    'moderní česká',
    'Stylová restaurace pod Karlovym mostem.',
    50.0865,
    14.4112,
    'https://www.cihelna.com/images/restaurace.jpg',
    NOW()
  ),
  (
    'sia-restaurant',
    'SIA Restaurant',
    'Praha 1',
    '🌿 PURE',
    'healthy / moderní',
    'Zdravá moderní kuchyně, sezónní ingredience.',
    50.0893,
    14.4267,
    'https://www.siarestaurant.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-modré-kachničky',
    'Restaurace U Modré kachničky',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace, romantická atmosféra.',
    50.0851,
    14.4089,
    'https://www.umodrekachnicky.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kalina-bar',
    'Kalina Bar',
    'Praha 7',
    '🌿 PURE',
    'moderní česká / bistro',
    'Moderní bistro s českou kuchyní, Ambiente awards.',
    50.0967,
    14.4401,
    'https://www.kalinabar.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-mlýnec',
    'Restaurace Mlýnec',
    'Praha 1',
    '🍷 LUXE',
    'moderní česká',
    'Restaurace s výhledem na Karlův most, kvalitní gastronomie.',
    50.0863,
    14.4121,
    'https://www.mlynec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'divinis',
    'Divinis',
    'Praha 1',
    '🍷 LUXE',
    'italská / vinárna',
    'Italská restaurace s vynikajícími víny.',
    50.0887,
    14.4189,
    'https://www.divinis.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'the-globe-bookstore-and-cafe',
    'The Globe Bookstore and Cafe',
    'Praha 7',
    '🌊 CALM',
    'kavárna / mezinárodní',
    'Kultovní knihkupectví s kavárnou, mezinárodní atmosféra.',
    50.0923,
    14.4378,
    'https://www.globebookstore.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'bistro-franz-kafka',
    'Bistro Franz Kafka',
    'Praha 1',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Bistro v centru s kvalitní kuchyní.',
    50.0883,
    14.4193,
    'https://www.bistrofranzkafka.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlaté-hrušky',
    'Restaurace U Zlaté hrušky',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Prahy.',
    50.0877,
    14.4205,
    'https://www.uzlatehrusky.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'buddha-bar',
    'Buddha Bar',
    'Praha 1',
    '🍷 LUXE',
    'asijská fúze',
    'Luxusní asijská restaurace s unikátní atmosférou.',
    50.0873,
    14.4213,
    'https://www.buddhabar.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 31-40
  (
    'restaurace-u-dvou-koček',
    'Restaurace U Dvou koček',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace v centru.',
    50.0885,
    14.4197,
    'https://www.udvoukotek.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'potrefená-husa-karlín',
    'Potrefená husa Karlín',
    'Praha 8',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Řetězec pivnic s českou klasikou a čerstvým pivem.',
    50.0912,
    14.4489,
    'https://www.potrefenahusa.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'sasazu',
    'SaSaZu',
    'Praha 7',
    '🍷 LUXE',
    'asijská / klub',
    'Luxusní asijská restaurace s klubem.',
    50.0945,
    14.4523,
    'https://www.sasazu.com/images/restaurace.jpg',
    NOW()
  ),
  (
    'coda-restaurant',
    'CODA Restaurant',
    'Praha 1',
    '🍷 LUXE',
    'fine dining / fusion',
    'Kreativní fine dining, Ambiente awards.',
    50.0867,
    14.4201,
    'https://www.codarestaurant.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-pinkasů',
    'U Pinkasů',
    'Praha 1',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Historická pivnice od roku 1843.',
    50.0821,
    14.4234,
    'https://www.upinkasu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-maltézských-rytířů',
    'Restaurace U Maltézských rytířů',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Malé Straně.',
    50.0858,
    14.4054,
    'https://www.umaltezskychrytiru.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'home-kitchen',
    'Home Kitchen',
    'Praha 2',
    '🌿 PURE',
    'healthy / mezinárodní',
    'Zdravá kuchyně s důrazem na kvalitu.',
    50.0789,
    14.4412,
    'https://www.homekitchen.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'la-bottega-bistroteka',
    'La Bottega Bistroteka',
    'Praha 2',
    '🌿 PURE',
    'italská / bistro',
    'Autentická italská kuchyně, bistro atmosféra.',
    50.0745,
    14.4367,
    'https://www.labottega.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kroka',
    'Restaurace U Kroka',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.0879,
    14.4185,
    'https://www.ukroka.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kantýna',
    'Kantýna',
    'Praha 7',
    '🌮 CHAOS',
    'česká kuchyně / moderní',
    'Moderní kantýna s českou kuchyní, oblíbená u místních.',
    50.0978,
    14.4423,
    'https://www.kantyna.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 41-50
  (
    'restaurace-u-sadů',
    'Restaurace U Sadů',
    'Praha 7',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace s českou klasikou.',
    50.0989,
    14.4401,
    'https://www.usadu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-grosseto-karlín',
    'Pizzeria Grosseto Karlín',
    'Praha 8',
    '🌿 PURE',
    'italská / pizza',
    'Autentická italská pizza z pece.',
    50.0923,
    14.4512,
    'https://www.grosseto.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-červeného-kola',
    'Restaurace U Červeného kola',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace v centru.',
    50.0891,
    14.4223,
    'https://www.ucervenehokola.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kuchyň',
    'Kuchyň',
    'Praha 8',
    '🌿 PURE',
    'moderní česká',
    'Moderní česká kuchyně v Karlíně.',
    50.0934,
    14.4501,
    'https://www.kuchyn.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'bistro-monk',
    'Bistro Monk',
    'Praha 2',
    '🌊 CALM',
    'česká / moderní',
    'Oblíbené bistro s kvalitní kuchyní.',
    50.0767,
    14.4389,
    'https://www.bistromonk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-krbu',
    'Restaurace U Krbu',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Útulná restaurace s krbem.',
    50.0865,
    14.4167,
    'https://www.ukrbu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'la-veranda',
    'La Veranda',
    'Praha 1',
    '🍷 LUXE',
    'mezinárodní / hotel',
    'Hotelová restaurace s mezinárodní kuchyní.',
    50.0871,
    14.4289,
    'https://www.laveranda.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zelené-žáby',
    'Restaurace U Zelené žáby',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru.',
    50.0883,
    14.4179,
    'https://www.uzelenezaby.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'depot-holešovice',
    'Depot Holešovice',
    'Praha 7',
    '🌮 CHAOS',
    'street food / food hall',
    'Food hall s různými koncepty, živá atmosféra.',
    50.1012,
    14.4456,
    'https://www.depot.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-provaznice',
    'Restaurace U Provaznice',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace se spolehlivou kuchyní.',
    50.0875,
    14.4193,
    'https://www.uprovaznice.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 51-60
  (
    'restaurace-u-medvídků',
    'Restaurace U Medvídků',
    'Praha 1',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Historický pivovar s restaurací, od roku 1466.',
    50.0831,
    14.4198,
    'https://www.umedvidku.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'dish-fine-burger-bistro',
    'Dish Fine Burger Bistro',
    'Praha 1',
    '🔥 DRAMA',
    'burger / bistro',
    'Prémiové burgery v centru Prahy.',
    50.0887,
    14.4245,
    'https://www.dish.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-pálffy-palác',
    'Restaurace Pálffy palác',
    'Praha 1',
    '🍷 LUXE',
    'moderní česká',
    'Stylová restaurace v historickém paláci.',
    50.0881,
    14.4034,
    'https://www.palffypalac.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'café-louvre',
    'Café Louvre',
    'Praha 1',
    '🌊 CALM',
    'česká / kavárna',
    'Historická kavárna od roku 1902, navštěvoval Einstein.',
    50.0819,
    14.4156,
    'https://www.cafelouvre.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'olympia-plzeňská-restaurace',
    'Olympia Plzeňská restaurace',
    'Praha 3',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice na Žižkově.',
    50.0834,
    14.4501,
    'https://www.olympia.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-bansethů',
    'Restaurace U Bansetů',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Prahy.',
    50.0869,
    14.4175,
    'https://www.ubansetu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'red-pif',
    'Red Pif',
    'Praha 2',
    '🔥 DRAMA',
    'burger / street food',
    'Oblíbený burger bar na Vinohradech.',
    50.0778,
    14.4434,
    'https://www.redpif.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-cisařů',
    'Restaurace U Císařů',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Historická restaurace v Malé Straně.',
    50.0867,
    14.4045,
    'https://www.ucisaru.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pastička',
    'Pastička',
    'Praha 7',
    '🌿 PURE',
    'italská / bistro',
    'Oblíbené italské bistro s čerstvými pastami.',
    50.0956,
    14.4389,
    'https://www.pasticka.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-baráčnická-rychta',
    'Restaurace Baráčnická rychta',
    'Praha 3',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na Žižkově.',
    50.0856,
    14.4523,
    'https://www.baracnickarychta.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 61-70
  (
    'u-houbaře',
    'U Houbaře',
    'Praha 3',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená žižkovská hospoda.',
    50.0889,
    14.4567,
    'https://www.uhoubare.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'café-imperial',
    'Café Imperial',
    'Praha 1',
    '🌊 CALM',
    'česká / mezinárodní',
    'Art Nouveau kavárna s vynikající kuchyní.',
    50.0897,
    14.4312,
    'https://www.cafeimperial.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-emy-destinnové',
    'Restaurace U Emy Destinnové',
    'Praha 2',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace na Vinohradech.',
    50.0756,
    14.4423,
    'https://www.uemydestinnove.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'lehká-hlava',
    'Lehká hlava',
    'Praha 1',
    '🌿 PURE',
    'vegetariánská',
    'První vegetariánská restaurace v Praze, od roku 2000.',
    50.0871,
    14.4145,
    'https://www.lehkahlava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'hanavský-pavilon',
    'Hanavský pavilon',
    'Praha 7',
    '🍷 LUXE',
    'moderní česká',
    'Stylová restaurace v pavilonu s výhledem na Prahu.',
    50.0945,
    14.4123,
    'https://www.hanavsky.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-kmotra',
    'Pizzeria Kmotra',
    'Praha 7',
    '🌿 PURE',
    'italská / pizza',
    'Oblíbená pizzerie v Holešovicích.',
    50.0989,
    14.4389,
    'https://www.kmotra.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-parlamentu-vinohrady',
    'U Parlamentu Vinohrady',
    'Praha 2',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace na Vinohradech.',
    50.0767,
    14.4401,
    'https://www.uparlamentu-vinohrady.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.0873,
    14.4187,
    'https://www.ukata-praha.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'bistro-štastný-smíchov',
    'Bistro Štastný Smíchov',
    'Praha 5',
    '🌿 PURE',
    'moderní česká / bistro',
    'Oblíbené bistro s kvalitní kuchyní.',
    50.0745,
    14.4012,
    'https://www.bistrostastny.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinohradský-parlament',
    'Vinohradský parlament',
    'Praha 2',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Pivnice s českou klasikou.',
    50.0778,
    14.4445,
    'https://www.vinohradskyparlament.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 71-80
  (
    'u-budyňské-brány',
    'U Budyňské brány',
    'Praha 3',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na Žižkově.',
    50.0867,
    14.4534,
    'https://www.ubudynskebrany.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-obecní-dům',
    'Restaurace Obecní dům',
    'Praha 1',
    '🍷 LUXE',
    'česká / Art Nouveau',
    'Luxusní restaurace v Obecním domě, jedinečná atmosféra.',
    50.0877,
    14.4278,
    'https://www.obecnidum.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura',
    'Restaurace U Kocoura',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.0881,
    14.4191,
    'https://www.ukocoura-praha.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'borgál',
    'Borgál',
    'Praha 1',
    '🌊 CALM',
    'česká / mezinárodní',
    'Oblíbená restaurace v centru.',
    50.0865,
    14.4209,
    'https://www.borgal.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-glaubiců',
    'U Glaubiců',
    'Praha 3',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Žižkovská hospoda s českou klasikou.',
    50.0878,
    14.4589,
    'https://www.uglaubicu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'lokál-nad-stromovkou',
    'Lokál Nad Stromovkou',
    'Praha 7',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Lokál u parku Stromovka.',
    50.1023,
    14.4234,
    'https://www.lokal-stromovka.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-suteru',
    'Restaurace U Suterů',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.0875,
    14.4183,
    'https://www.usuteru.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-slavia',
    'Kavárna Slavia',
    'Praha 1',
    '🌊 CALM',
    'česká / kavárna',
    'Legendární kavárna s výhledem na Národní divadlo.',
    50.0817,
    14.4123,
    'https://www.cafeslavia.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'noi',
    'Noi',
    'Praha 7',
    '🌿 PURE',
    'asijská / healthy',
    'Zdravá asijská kuchyně.',
    50.0945,
    14.4378,
    'https://www.noi.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-sádů-dejvice',
    'Restaurace U Sádů Dejvice',
    'Praha 6',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v Dejvicích.',
    50.0989,
    14.3912,
    'https://www.usadu-dejvice.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 81-90
  (
    'u-zavěšenýho-kafe',
    'U Zavěšenýho kafe',
    'Praha 3',
    '🌮 CHAOS',
    'česká kuchyně / hospoda',
    'Autentická žižkovská hospoda.',
    50.0845,
    14.4612,
    'https://www.uzavesenyhokafe.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-da-emanuel',
    'Pizzeria da Emanuel',
    'Praha 7',
    '🌿 PURE',
    'italská / pizza',
    'Autentická italská pizza.',
    50.0967,
    14.4412,
    'https://www.daemanuel.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-schnellů',
    'Restaurace U Schnellů',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.0869,
    14.4195,
    'https://www.uschnellu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'krystal-mozaika-bistro',
    'Krystal Mozaika Bistro',
    'Praha 1',
    '🌊 CALM',
    'česká / mezinárodní',
    'Bistro s kvalitní kuchyní.',
    50.0893,
    14.4289,
    'https://www.krystalmozaika.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-houbaře-vinohrady',
    'Restaurace U Houbaře Vinohrady',
    'Praha 2',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace na Vinohradech.',
    50.0734,
    14.4389,
    'https://www.uhoubare-vinohrady.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-zlatého-jelena',
    'U Zlatého jelena',
    'Praha 7',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Holešovicích.',
    50.0978,
    14.4401,
    'https://www.uzlatehojelena.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlaté-koruny',
    'Restaurace U Zlaté koruny',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.0871,
    14.4189,
    'https://www.uzlatekoruny-praha.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kolkovna-olympia',
    'Kolkovna Olympia',
    'Praha 1',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Řetězec pivnic s českou klasikou.',
    50.0883,
    14.4267,
    'https://www.kolkovna.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-rudolfina',
    'U Rudolfina',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace u Rudolfina.',
    50.0901,
    14.4156,
    'https://www.urudolfina.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'cross-club',
    'Cross Club',
    'Praha 7',
    '🌮 CHAOS',
    'bar / klub',
    'Kultovní klub s barem a občerstvením.',
    50.1012,
    14.4501,
    'https://www.crossclub.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 91-100
  (
    'restaurace-u-dvou-medvědů',
    'Restaurace U Dvou medvědů',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.0867,
    14.4179,
    'https://www.udvoumedvedu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-bílého-lva',
    'Restaurace U Bílého lva',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v centru.',
    50.0873,
    14.4193,
    'https://www.ubileho-lva.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-kunštátů',
    'U Kunštátů',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v historickém domě.',
    50.0877,
    14.4185,
    'https://www.ukunstatu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-magistra-kelly',
    'Restaurace U Magistra Kelly',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru.',
    50.0869,
    14.4197,
    'https://www.umagistrakelly.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivovarský-dům',
    'Pivovarský dům',
    'Praha 2',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Minipivovar s netradičními pivními specialitami.',
    50.0745,
    14.4201,
    'https://www.pivovarskydum.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-tří-růží',
    'U Tří růží',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.0875,
    14.4191,
    'https://www.utriruzi-praha.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-prince',
    'Restaurace U Prince',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace se střešní terasou a výhledem na Orloj.',
    50.0871,
    14.4201,
    'https://www.uprince.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlaté-studně',
    'Restaurace U Zlaté studně',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace v Malé Straně.',
    50.0879,
    14.4027,
    'https://www.uzlatestudne.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'u-vejvodů',
    'U Vejvodů',
    'Praha 1',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Historická pivnice v centru Prahy.',
    50.0825,
    14.4167,
    'https://www.uvejvodu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kalendů',
    'Restaurace U Kalendů',
    'Praha 1',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace s dlouhou historií.',
    50.0871,
    14.4195,
    'https://www.ukalendu.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
