-- Import restaurací STŘEDOČESKÝ KRAJ 1–80 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10
  (
    'restaurace-zamek-mcely',
    'Restaurace Zámek Mčely',
    'Mčely',
    '🍷 LUXE',
    'fine dining / zámecká restaurace',
    'Exkluzivní restaurace v barokním zámku, špičková gastronomie.',
    50.2589,
    15.0234,
    'https://www.zamek-mcely.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-stara-myslivna',
    'Restaurace Stará myslivna',
    'Kutná Hora',
    '🍷 LUXE',
    'fine dining / moderní česká',
    'Nejvýznamnější gastronomická adresa Kutné Hory, kreativní kuchyně.',
    49.9483,
    15.2680,
    'https://www.staramyslivna.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-hrnčíře',
    'Restaurace U Hrnčíře',
    'Kutná Hora',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru města, česká klasika.',
    49.9487,
    15.2677,
    'https://www.uhrncire.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-vlašského-dvora',
    'Restaurace U Vlašského dvora',
    'Kutná Hora',
    '🌊 CALM',
    'česká kuchyně',
    'Historická restaurace u významné památky, česká klasika.',
    49.9491,
    15.2673,
    'https://www.uvlasskehodvora.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-dačický',
    'Restaurace Dačický',
    'Kutná Hora',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní a vinným sklípkem.',
    49.9479,
    15.2685,
    'https://www.dacicky.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-v-ruthardce',
    'Restaurace V Ruthardce',
    'Kutná Hora',
    '🌿 PURE',
    'česká / regionální kuchyně',
    'Poctivá restaurace s tradičními recepty a domácí atmosférou.',
    49.9475,
    15.2689,
    'https://www.vruthardce.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-dačického',
    'Pivnice Dačického',
    'Kutná Hora',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Živá hospoda s dobrým pivem a českou klasikou.',
    49.9481,
    15.2681,
    'https://www.pivnicedacickeho.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-harmonia',
    'Restaurace Harmonia',
    'Kutná Hora',
    '🌊 CALM',
    'česká / italská kuchyně',
    'Oblíbená restaurace s širokým menu a příjemnou atmosférou.',
    49.9485,
    15.2675,
    'https://www.harmonia-kh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Kutná Hora',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v historickém domě, spolehlivá kuchyně.',
    49.9489,
    15.2671,
    'https://www.ukata-kh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-supremo',
    'Restaurace Supremo',
    'Kutná Hora',
    '🌿 PURE',
    'italská kuchyně / pizza',
    'Oblíbená italská restaurace s autentickou kuchyní.',
    49.9477,
    15.2687,
    'https://www.supremo-kh.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20
  (
    'restaurace-u-cerneho-orla-mb',
    'Restaurace U Černého orla',
    'Mladá Boleslav',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru města, česká klasika.',
    50.4111,
    14.9033,
    'https://www.ucernehoorla-mb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda-mb',
    'Restaurace Beseda',
    'Mladá Boleslav',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou a klidnou atmosférou.',
    50.4115,
    14.9029,
    'https://www.beseda-mb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-skoda-muzeum',
    'Restaurace Škoda Muzeum',
    'Mladá Boleslav',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Moderní restaurace v muzeu Škoda Auto, kvalitní gastronomie.',
    50.4089,
    14.9101,
    'https://www.skoda-muzeum.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-centrál-mb',
    'Restaurace Centrál',
    'Mladá Boleslav',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s tradičními recepty.',
    50.4107,
    14.9037,
    'https://www.central-mb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-kasny',
    'Pivnice U Kašny',
    'Mladá Boleslav',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českou klasikou.',
    50.4113,
    14.9031,
    'https://www.ukasny.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-hotel-pyramida',
    'Restaurace Hotel Pyramida',
    'Mladá Boleslav',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s širokim menu a příjemnou atmosférou.',
    50.4095,
    14.9067,
    'https://www.pyramida-mb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-pivovarská-bašta',
    'Restaurace Pivovarská bašta',
    'Mladá Boleslav',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Pivovarnická restaurace s vlastním pivem, živá atmosféra.',
    50.4109,
    14.9035,
    'https://www.pivovarska-basta.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-rychtáře',
    'Restaurace U Rychtáře',
    'Mladá Boleslav',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v centru, spolehlivá česká kuchyně.',
    50.4117,
    14.9027,
    'https://www.urychtare-mb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zlatá-koruna',
    'Restaurace Zlatá koruna',
    'Mladá Boleslav',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s domácí atmosférou a tradičními pokrmy.',
    50.4105,
    14.9039,
    'https://www.zlatakoruna-mb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-tempo',
    'Restaurace Tempo',
    'Mladá Boleslav',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Oblíbená restaurace s širokým menu.',
    50.4099,
    14.9051,
    'https://www.tempo-mb.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-30
  (
    'restaurace-stará-pošta-kolin',
    'Restaurace Stará pošta',
    'Kolín',
    '🌊 CALM',
    'česká kuchyně',
    'Historická restaurace v centru města, česká klasika.',
    50.0282,
    15.2011,
    'https://www.staraposta-kolin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-kolin',
    'Restaurace U Radnice',
    'Kolín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí, spolehlivá kuchyně.',
    50.0285,
    15.2008,
    'https://www.uradnice-kolin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-karlštejn-kolin',
    'Restaurace Karlštejn',
    'Kolín',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní.',
    50.0278,
    15.2015,
    'https://www.karlstejn-kolin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-cerného-medvěda',
    'Pivnice U Černého medvěda',
    'Kolín',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    50.0280,
    15.2013,
    'https://www.ucernehomeveda-kolin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-sport-kolin',
    'Restaurace Sport',
    'Kolín',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s českou klasikou.',
    50.0275,
    15.2018,
    'https://www.sport-kolin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzerie-venezia-kolin',
    'Pizzerie Venezia',
    'Kolín',
    '🌿 PURE',
    'italská kuchyně / pizza',
    'Oblíbená italská restaurace s pizzou a pastami.',
    50.0287,
    15.2006,
    'https://www.venezia-kolin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlatého-lva-benesov',
    'Restaurace U Zlatého lva',
    'Benešov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Benešova, česká klasika.',
    49.7815,
    14.6871,
    'https://www.uzlateho-lva-benesov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-koníček-benesov',
    'Restaurace Koníček',
    'Benešov',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní a příjemnou atmosférou.',
    49.7819,
    14.6867,
    'https://www.konicek-benesov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-cerneho-koníčka',
    'Restaurace U Černého koníčka',
    'Benešov',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s tradičními recepty a domácí atmosférou.',
    49.7813,
    14.6873,
    'https://www.ucernehokoncka-benesov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-na-náměstí-benesov',
    'Pivnice Na náměstí',
    'Benešov',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českou klasikou.',
    49.7817,
    14.6869,
    'https://www.nanamesti-benesov.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 31-40
  (
    'restaurace-u-semíka',
    'Restaurace U Semíka',
    'Kladno',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická kladenská restaurace, česká klasika.',
    50.1427,
    14.1028,
    'https://www.usemika.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-centrál-kladno',
    'Restaurace Centrál',
    'Kladno',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Tradiční restaurace v centru města, široké menu.',
    50.1431,
    14.1024,
    'https://www.central-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-mistra-jana-husa',
    'Restaurace U Mistra Jana Husa',
    'Kladno',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.1425,
    14.1030,
    'https://www.umistrajana-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-dvou-koček',
    'Pivnice U Dvou koček',
    'Kladno',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    50.1429,
    14.1026,
    'https://www.udvoukocev-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-golf-kladno',
    'Restaurace Golf',
    'Kladno',
    '🌿 PURE',
    'česká / mezinárodní kuchyně',
    'Restaurace u golfového hřiště s kvalitní kuchyní.',
    50.1389,
    14.1101,
    'https://www.golf-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-U-sluneční-brány',
    'Restaurace U Sluneční brány',
    'Kladno',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace s českou kuchyní.',
    50.1433,
    14.1022,
    'https://www.uslunecnibrany-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-vodárny',
    'Restaurace U Vodárny',
    'Kladno',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s domácí atmosférou.',
    50.1401,
    14.1067,
    'https://www.uvodarny-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzerie-venezia-kladno',
    'Pizzerie Venezia',
    'Kladno',
    '🌿 PURE',
    'italská kuchyně / pizza',
    'Oblíbená italská restaurace s pizzou a pastami.',
    50.1435,
    14.1020,
    'https://www.venezia-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-města-kladna',
    'Restaurace U Města Kladna',
    'Kladno',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru, spolehlivá česká kuchyně.',
    50.1423,
    14.1032,
    'https://www.umestakladna.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurant-black-horse-kladno',
    'Restaurant Black Horse',
    'Kladno',
    '🍷 LUXE',
    'fine dining / moderní česká',
    'Nejvýznamnější fine-dining adresa v Kladně.',
    50.1437,
    14.1018,
    'https://www.blackhorse-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 41-50
  (
    'restaurace-u-cerneho-orla-melnik',
    'Restaurace U Černého orla',
    'Mělník',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Mělníka, česká klasika.',
    50.3509,
    14.4738,
    'https://www.ucernehoorla-melnik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zamek-melnik',
    'Restaurace Zámek Mělník',
    'Mělník',
    '🍷 LUXE',
    'fine dining / vinařská kuchyně',
    'Exkluzivní restaurace na mělnickém zámku, kvalitní vína.',
    50.3513,
    14.4734,
    'https://www.zamek-melnik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-stará-škola-melnik',
    'Restaurace Stará škola',
    'Mělník',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.3507,
    14.4740,
    'https://www.staraskola-melnik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-U-orloje',
    'Pivnice U Orloje',
    'Mělník',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    50.3511,
    14.4736,
    'https://www.uorloje-melnik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-ludmila',
    'Restaurace Ludmila',
    'Mělník',
    '🌿 PURE',
    'česká / regionální kuchyně',
    'Rodinná restaurace s tradičními recepty.',
    50.3505,
    14.4742,
    'https://www.ludmila-melnik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-salabka',
    'Vinárna Salabka',
    'Mělník',
    '🍷 LUXE',
    'vinařská kuchyně',
    'Stylová vinárna s kvalitní gastronomií.',
    50.3515,
    14.4732,
    'https://www.salabka-melnik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-pribram',
    'Restaurace U Radnice',
    'Příbram',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí, česká klasika.',
    49.6895,
    14.0107,
    'https://www.uradnice-pribram.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-modrá-hvězda-pribram',
    'Restaurace Modrá hvězda',
    'Příbram',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní.',
    49.6899,
    14.0103,
    'https://www.modrahvezda-pribram.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zlatý-anděl',
    'Restaurace Zlatý anděl',
    'Příbram',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    49.6893,
    14.0109,
    'https://www.zlatyandel-pribram.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-hory',
    'Pivnice U Hory',
    'Příbram',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českým pivem.',
    49.6897,
    14.0105,
    'https://www.uhory-pribram.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 51-60
  (
    'restaurace-U-cerneho-orla-beroun',
    'Restaurace U Černého orla',
    'Beroun',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Berouna, česká klasika.',
    49.9639,
    14.0721,
    'https://www.ucernehoorla-beroun.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-cent-beroun',
    'Restaurace Cent',
    'Beroun',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní.',
    49.9643,
    14.0717,
    'https://www.cent-beroun.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-rychtě-beroun',
    'Restaurace Na rychtě',
    'Beroun',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s tradičními recepty.',
    49.9641,
    14.0719,
    'https://www.narychte-beroun.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-kocoura-beroun',
    'Pivnice U Kocoura',
    'Beroun',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    49.9637,
    14.0723,
    'https://www.ukocoura-beroun.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlaté-podkovy',
    'Restaurace U Zlaté podkovy',
    'Beroun',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace se spolehlivou českou kuchyní.',
    49.9645,
    14.0715,
    'https://www.uzlatepodkovy-beroun.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-karlštejn-beroun',
    'Restaurace Karlštejn',
    'Beroun',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    49.9635,
    14.0725,
    'https://www.karlstejn-beroun.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kasny-ricany',
    'Restaurace U Kašny',
    'Říčany',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Říčan, česká klasika.',
    49.9917,
    14.6544,
    'https://www.ukasny-ricany.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-golf-ricany',
    'Restaurace Golf',
    'Říčany',
    '🌿 PURE',
    'česká / mezinárodní kuchyně',
    'Restaurace u golfového hřiště s kvalitní kuchyní.',
    49.9872,
    14.6631,
    'https://www.golf-ricany.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzerie-venezia-ricany',
    'Pizzerie Venezia',
    'Říčany',
    '🌿 PURE',
    'italská kuchyně / pizza',
    'Oblíbená italská restaurace s pizzou a pastami.',
    49.9921,
    14.6540,
    'https://www.venezia-ricany.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-nová-myslivna',
    'Restaurace Nová myslivna',
    'Říčany',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou a klidnou atmosférou.',
    49.9889,
    14.6598,
    'https://www.novamyslivna-ricany.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 61-70
  (
    'restaurace-u-prince-cernosice',
    'Restaurace U Prince',
    'Černošice',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v centru Černošic, česká klasika.',
    49.9611,
    14.3183,
    'https://www.uprince-cernosice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-golf-cernosice',
    'Restaurace Golf',
    'Černošice',
    '🌿 PURE',
    'česká / mezinárodní kuchyně',
    'Restaurace u golfového hřiště s krásným výhledem.',
    49.9551,
    14.3278,
    'https://www.golf-cernosice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-vodáka',
    'Pivnice U Vodáka',
    'Černošice',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    49.9615,
    14.3179,
    'https://www.uvodaka-cernosice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-brandys',
    'Restaurace U Radnice',
    'Brandýs nad Labem',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí, česká klasika.',
    50.1872,
    14.6633,
    'https://www.uradnice-brandys.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura-brandys',
    'Restaurace U Kocoura',
    'Brandýs nad Labem',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.1876,
    14.6629,
    'https://www.ukocoura-brandys.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-na-náměstí-brandys',
    'Pivnice Na náměstí',
    'Brandýs nad Labem',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českým pivem.',
    50.1870,
    14.6635,
    'https://www.nanamesti-brandys.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zamek-podebrady',
    'Restaurace Zámek',
    'Poděbrady',
    '🍷 LUXE',
    'moderní česká',
    'Stylová restaurace na poděbradském zámku.',
    50.1425,
    15.1188,
    'https://www.zamek-podebrady.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-bellevue-podebrady',
    'Restaurace Bellevue',
    'Poděbrady',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Lázeňská restaurace s kvalitní kuchyní.',
    50.1429,
    15.1184,
    'https://www.bellevue-podebrady.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-zlaté-koruny',
    'Pivnice U Zlaté koruny',
    'Poděbrady',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    50.1423,
    15.1190,
    'https://www.uzlatekoruny-podebrady.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-cerneho-orla-rakovnik',
    'Restaurace U Černého orla',
    'Rakovník',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Rakovníka, česká klasika.',
    50.1037,
    13.7333,
    'https://www.ucernehoorla-rakovnik.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 71-80
  (
    'restaurace-u-bílého-koně',
    'Restaurace U Bílého koně',
    'Rakovník',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.1041,
    13.7329,
    'https://www.ubilehokone-rakovnik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-krále',
    'Pivnice U Krále',
    'Rakovník',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českým pivem.',
    50.1039,
    13.7331,
    'https://www.ukrale-rakovnik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-nymburk',
    'Restaurace U Radnice',
    'Nymburk',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí, česká klasika.',
    50.1861,
    15.0417,
    'https://www.uradnice-nymburk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura-nymburk',
    'Restaurace U Kocoura',
    'Nymburk',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.1865,
    15.0413,
    'https://www.ukocoura-nymburk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-vodárny-nymburk',
    'Pivnice U Vodárny',
    'Nymburk',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    50.1863,
    15.0415,
    'https://www.uvodarny-nymburk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlateho-jelena',
    'Restaurace U Zlatého jelena',
    'Benešov',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace se spolehlivou českou kuchyní.',
    49.7811,
    14.6875,
    'https://www.uzlatehojelena-benesov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-golf-benesov',
    'Restaurace Golf',
    'Benešov',
    '🌿 PURE',
    'česká / mezinárodní kuchyně',
    'Restaurace u golfového hřiště s kvalitní kuchyní.',
    49.7768,
    14.6934,
    'https://www.golf-benesov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-parlamentu-kladno',
    'Restaurace U Parlamentu',
    'Kladno',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou a klidnou atmosférou.',
    50.1421,
    14.1034,
    'https://www.uparlamentu-kladno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-pod-věží',
    'Restaurace Pod věží',
    'Příbram',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s tradičními recepty a domácí atmosférou.',
    49.6891,
    14.0111,
    'https://www.podvezi-pribram.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-bílého-koníčka-pribram',
    'Restaurace U Bílého koníčka',
    'Příbram',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v centru města, česká klasika.',
    49.6901,
    14.0101,
    'https://www.ubilehokonicka-pribram.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
