-- Import restaurací PLZEŇSKÝ KRAJ 1–50 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10
  (
    'restaurant-black-horse',
    'Restaurant Black Horse',
    'Plzeň',
    '🍷 LUXE',
    'fine dining / moderní česká',
    'Nejvýznamnější fine-dining adresa v Plzni, moderní česká kuchyně a precizní servis.',
    49.7478,
    13.3775,
    'https://www.blackhorse.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-spilce',
    'Restaurace Na Spilce',
    'Plzeň',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Legendární pivovarnická restaurace Plzeňského Prazdroje, živá atmosféra.',
    49.7425,
    13.3891,
    'https://www.naspilce.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-salzmannu',
    'Restaurace U Salzmannů',
    'Plzeň',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční plzeňská restaurace s dlouhou historií, spolehlivá česká klasika.',
    49.7471,
    13.3782,
    'https://www.usalzmannu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-andel',
    'Restaurace Anděl',
    'Plzeň',
    '🍷 LUXE',
    'moderní evropská kuchyně',
    'Elegantní hotelová restaurace v centru města, kvalitní gastronomie.',
    49.7485,
    13.3768,
    'https://www.andel-plzen.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-mestanska-beseda',
    'Restaurace Měšťanská beseda',
    'Plzeň',
    '🌊 CALM',
    'česká kuchyně',
    'Historická restaurace v krásných prostorách, česká klasika a kulturní atmosféra.',
    49.7481,
    13.3771,
    'https://www.mestanskabeseda.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-rango',
    'Restaurace Rango',
    'Plzeň',
    '🌿 PURE',
    'česká / mexická kuchyně',
    'Oblíbená restaurace s mexickým vlivem a českou klasikou.',
    49.7489,
    13.3795,
    'https://www.rango.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-mansfelda',
    'Pivnice U Mansfelda',
    'Plzeň',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Klasická plzeňská hospoda s dobrým pivem a živou atmosférou.',
    49.7476,
    13.3789,
    'https://www.umansfelda.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-bookmakers',
    'Restaurace U Bookmakers',
    'Plzeň',
    '🌊 CALM',
    'česká / americká kuchyně',
    'Sportovní restaurace s širokým menu a příjemnou atmosférou.',
    49.7492,
    13.3801,
    'https://www.ubookmakers.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-tri-ruzí',
    'Restaurace U Tří růží',
    'Klatovy',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Klatov, česká klasika a klidné prostředí.',
    49.3958,
    13.2951,
    'https://www.utriruzi.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-central',
    'Restaurace Central',
    'Klatovy',
    '🍷 LUXE',
    'moderní česká',
    'Hotelová restaurace s kvalitní kuchyní a moderním přístupem.',
    49.3962,
    13.2947,
    'https://www.central-klatovy.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20
  (
    'restaurace-u-cerneho-orla',
    'Restaurace U Černého orla',
    'Domažlice',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v historickém centru, spolehlivá česká kuchyně.',
    49.4401,
    12.9298,
    'https://www.ucerneho-orla-domazlice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-korunni-princ',
    'Restaurace Korunní princ',
    'Domažlice',
    '🍷 LUXE',
    'moderní česká / fine dining',
    'Elegantní hotelová restaurace s kvalitní gastronomií.',
    49.4405,
    12.9302,
    'https://www.korunniprinc.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlateho-lva',
    'Restaurace U Zlatého lva',
    'Tachov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru města, poctivá česká klasika.',
    49.7958,
    12.6341,
    'https://www.uzlateho-lva-tachov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-municipal-house',
    'Restaurace Municipal House',
    'Plzeň',
    '🍷 LUXE',
    'moderní evropská kuchyně',
    'Stylová restaurace s mezinárodním menu a kvalitním servisem.',
    49.7483,
    13.3779,
    'https://www.municipalhouse.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-parlamentu',
    'Restaurace U Parlamentu',
    'Plzeň',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou, klidná atmosféra.',
    49.7487,
    13.3793,
    'https://www.uparlamentu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-parkanu',
    'Restaurace Na Parkánu',
    'Plzeň',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Pivovarnická restaurace s vlastním pivem, živá atmosféra.',
    49.7469,
    13.3785,
    'https://www.naparkanu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zeleného-stromu',
    'Restaurace U Zeleného stromu',
    'Rokycany',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v centru Rokycan, spolehlivá kuchyně.',
    49.7429,
    13.5947,
    'https://www.uzelenehostromu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda',
    'Restaurace Beseda',
    'Rokycany',
    '🌿 PURE',
    'česká / regionální kuchyně',
    'Rodinná restaurace s tradičními recepty a domácí atmosférou.',
    49.7433,
    13.5951,
    'https://www.beseda-rokycany.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura',
    'Restaurace U Kocoura',
    'Stříbro',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru města, česká klasika.',
    49.7543,
    13.0028,
    'https://www.ukocoura-stribro.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurant-zlatá-hvezda',
    'Restaurant Zlatá hvězda',
    'Stříbro',
    '🍷 LUXE',
    'moderní česká',
    'Hotelová restaurace s kvalitní kuchyní a elegantním prostředím.',
    49.7547,
    13.0032,
    'https://www.zlatahvezda-stribro.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-30
  (
    'restaurace-u-holuba',
    'Restaurace U Holuba',
    'Plzeň',
    '🌿 PURE',
    'česká kuchyně',
    'Poctivá česká restaurace s rodinnou atmosférou.',
    49.7474,
    13.3797,
    'https://www.uholuba.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzerie-ristorante-grosseto',
    'Pizzerie Ristorante Grosseto',
    'Plzeň',
    '🌿 PURE',
    'italská kuchyně / pizza',
    'Oblíbená italská restaurace s autentickou kuchyní.',
    49.7495,
    13.3788,
    'https://www.grosseto.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-groll',
    'Restaurace Groll',
    'Plzeň',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace v pivovarnickém stylu, česká klasika a pivo.',
    49.7428,
    13.3896,
    'https://www.groll.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-U-royal',
    'Restaurace U Royal',
    'Plzeň',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s širokým menu a příjemnou atmosférou.',
    49.7491,
    13.3773,
    'https://www.uroyal.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-bílého-koníčka',
    'Restaurace U Bílého koníčka',
    'Klatovy',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s tradičními recepty a klidnou atmosférou.',
    49.3954,
    13.2958,
    'https://www.ubilehokonicka-klatovy.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-zamecku',
    'Restaurace Na Zámečku',
    'Klatovy',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s výhledem, česká klasika.',
    49.3965,
    13.2942,
    'https://www.nazamecku.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-stará-radnice',
    'Restaurace Stará radnice',
    'Domažlice',
    '🌊 CALM',
    'česká kuchyně',
    'Historická restaurace na náměstí, česká klasika a klidné prostředí.',
    49.4398,
    12.9306,
    'https://www.stararadnice-domazlice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-čtyř-kohoutů',
    'Restaurace U Čtyř kohoutů',
    'Domažlice',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českou klasikou.',
    49.4408,
    12.9295,
    'https://www.uctyrkohoutu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zámku',
    'Restaurace U Zámku',
    'Tachov',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace v blízkosti zámku, spolehlivá česká kuchyně.',
    49.7962,
    12.6338,
    'https://www.uzamku-tachov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-náměstí',
    'Restaurace Na náměstí',
    'Tachov',
    '🌿 PURE',
    'česká / regionální kuchyně',
    'Klasická restaurace s tradičními pokrmy a domácí atmosférou.',
    49.7955,
    12.6345,
    'https://www.nanamesti-tachov.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 31-40
  (
    'restaurace-sklipek',
    'Restaurace Sklípek',
    'Plzeň',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace ve sklepních prostorách, česká klasika a příjemná atmosféra.',
    49.7479,
    13.3786,
    'https://www.sklipek-plzen.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-purkmistr',
    'Restaurace Purkmistr',
    'Plzeň',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Pivovarnická restaurace s vlastním pivem, živá atmosféra.',
    49.7457,
    13.3812,
    'https://www.purkmistr.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-dvou-medvídků',
    'Restaurace U Dvou medvídků',
    'Plzeň',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou a rodinnou atmosférou.',
    49.7485,
    13.3791,
    'https://www.udvoumedvidku.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-continental',
    'Restaurace Continental',
    'Plzeň',
    '🍷 LUXE',
    'moderní evropská kuchyně',
    'Elegantní hotelová restaurace s mezinárodním menu.',
    49.7488,
    13.3765,
    'https://www.continental-plzen.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Rokycany',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českou klasikou.',
    49.7426,
    13.5954,
    'https://www.ukata-rokycany.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-kopci',
    'Restaurace Na kopci',
    'Rokycany',
    '🌿 PURE',
    'česká kuchyně',
    'Restaurace s výhledem na město, poctivá kuchyně.',
    49.7441,
    13.5938,
    'https://www.nakopci-rokycany.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice',
    'Restaurace U Radnice',
    'Stříbro',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace na náměstí, česká klasika.',
    49.7541,
    13.0035,
    'https://www.uradnice-stribro.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-mlýně',
    'Restaurace Na mlýně',
    'Stříbro',
    '🌿 PURE',
    'česká / regionální kuchyně',
    'Restaurace v historickém mlýně, tradiční recepty.',
    49.7536,
    13.0042,
    'https://www.namlyne-stribro.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zlatý-beránek',
    'Restaurace Zlatý beránek',
    'Klatovy',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru města, spolehlivá kuchyně.',
    49.3951,
    13.2962,
    'https://www.zlatyberanek.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-růže',
    'Restaurace U Růže',
    'Klatovy',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s domácí atmosférou a tradičními pokrmy.',
    49.3967,
    13.2938,
    'https://www.uruze-klatovy.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 41-50
  (
    'restaurace-na-starém-městě',
    'Restaurace Na starém městě',
    'Plzeň',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v historickém centru, česká klasika.',
    49.7482,
    13.3776,
    'https://www.nastaremmeste.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-jelena',
    'Restaurace U Jelena',
    'Domažlice',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace s českou kuchyní a klidnou atmosférou.',
    49.4395,
    12.9310,
    'https://www.ujelena-domazlice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-modrá-hvězda',
    'Restaurace Modrá hvězda',
    'Domažlice',
    '🌿 PURE',
    'česká / regionální kuchyně',
    'Rodinná restaurace s tradičními recepty a domácí atmosférou.',
    49.4412,
    12.9292,
    'https://www.modrahvezda-domazlice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-anděla',
    'Restaurace U Anděla',
    'Tachov',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru města, spolehlivá česká klasika.',
    49.7951,
    12.6349,
    'https://www.uandela-tachov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzerie-venezia',
    'Pizzerie Venezia',
    'Plzeň',
    '🌿 PURE',
    'italská kuchyně / pizza',
    'Oblíbená italská restaurace s pizzou a pastami.',
    49.7493,
    13.3802,
    'https://www.venezia-plzen.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-ševce',
    'Restaurace U Ševce',
    'Plzeň',
    '🌮 CHAOS',
    'česká kuchyně / hospoda',
    'Hospoda s českou klasikou a živou atmosférou.',
    49.7472,
    13.3799,
    'https://www.usevce.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia',
    'Restaurace Slavia',
    'Rokycany',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v centru města, česká klasika.',
    49.7437,
    13.5943,
    'https://www.slavia-rokycany.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-rychtě',
    'Restaurace Na rychtě',
    'Stříbro',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace s českou kuchyní a příjemnou atmosférou.',
    49.7545,
    13.0026,
    'https://www.narycht-stribro.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-panorama',
    'Restaurace Panorama',
    'Klatovy',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace s výhledem na město, česká klasika a klidné prostředí.',
    49.3971,
    13.2935,
    'https://www.panorama-klatovy.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-selsky-dvur',
    'Restaurace Selský dvůr',
    'Plzeň',
    '🌿 PURE',
    'česká / venkovská kuchyně',
    'Venkovská restaurace s rustikálním interiérem a tradičními pokrmy.',
    49.7465,
    13.3818,
    'https://www.selskydvur-plzen.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
