-- Import restaurací MORAVSKOSLEZSKÝ KRAJ 1–80 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10 Ostrava (třetí největší město)
  (
    'restaurant-dado',
    'Restaurant DaDo',
    'Ostrava',
    '🍷 LUXE',
    'fine dining / moderní',
    'Nejlepší fine dining v Ostravě, kreativní kuchyně.',
    49.8351,
    18.2820,
    'https://www.dado-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurant-black-horse',
    'Restaurant Black Horse',
    'Ostrava',
    '🍷 LUXE',
    'fine dining / steakhouse',
    'Luxusní steakhouse s prémiovým masem.',
    49.8356,
    18.2834,
    'https://www.blackhorse-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-cerná-louka',
    'Restaurace Černá louka',
    'Ostrava',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Ostravy.',
    49.8312,
    18.2789,
    'https://www.cernalouka.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-svejka',
    'Pivnice U Švejka',
    'Ostrava',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice s českou klasikou.',
    49.8367,
    18.2845,
    'https://www.usvejka-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-harmonie',
    'Restaurace Harmonie',
    'Ostrava',
    '🌊 CALM',
    'česká / mezinárodní',
    'Restaurace s českou a mezinárodní kuchyní.',
    49.8345,
    18.2812,
    'https://www.harmonie-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-grosseto-ostrava',
    'Pizzeria Grosseto',
    'Ostrava',
    '🌿 PURE',
    'italská / pizza',
    'Autentická italská pizza z pece.',
    49.8378,
    18.2867,
    'https://www.grosseto-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-golem',
    'Restaurace Golem',
    'Ostrava',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v Ostravě.',
    49.8334,
    18.2798,
    'https://www.golem-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivovarska-restaurace-zlatovar',
    'Pivovarská restaurace Zlatovar',
    'Ostrava',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Minipivovar s vlastním pivem a českou klasikou.',
    49.8389,
    18.2889,
    'https://www.zlatovar.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-rango',
    'Steakhouse Rango',
    'Ostrava',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v centru města.',
    49.8362,
    18.2823,
    'https://www.rango-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-restaurant-vina',
    'Asia Restaurant Vina',
    'Ostrava',
    '🌿 PURE',
    'asijská / sushi',
    'Asijská kuchyně a sushi v Ostravě.',
    49.8373,
    18.2856,
    'https://www.vina-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20 Ostrava pokračování
  (
    'restaurace-u-krale-brabantskeho',
    'Restaurace U Krále brabantského',
    'Ostrava',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    49.8341,
    18.2801,
    'https://www.ukralebrabant.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurant-imperial',
    'Restaurant Imperial',
    'Ostrava',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Luxusní hotelová restaurace.',
    49.8358,
    18.2829,
    'https://www.imperial-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'cukrárna-a-kavárna-miramor',
    'Cukrárna a Kavárna Miramor',
    'Ostrava',
    '🌊 CALM',
    'kavárna / dezerty',
    'Historická kavárna s vynikajícími dezerty.',
    49.8349,
    18.2817,
    'https://www.miramor.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-balbínku',
    'Restaurace U Balbínku',
    'Ostrava',
    '🌮 CHAOS',
    'česká kuchyně / hospoda',
    'Oblíbená hospoda s domácí kuchyní.',
    49.8381,
    18.2873,
    'https://www.ubalbinku.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'bistro-franz',
    'Bistro Franz',
    'Ostrava',
    '🌿 PURE',
    'moderní / bistro',
    'Moderní bistro s kvalitní kuchyní.',
    49.8365,
    18.2841,
    'https://www.franz-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-stará-aréna',
    'Restaurace Stará aréna',
    'Ostrava',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace u hokejové haly.',
    49.8298,
    18.2756,
    'https://www.staraarena.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-inn',
    'Burger Inn',
    'Ostrava',
    '🔥 DRAMA',
    'burger / fast casual',
    'Oblíbený burger bar v Ostravě.',
    49.8371,
    18.2849,
    'https://www.burgerinn.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-černého-orla',
    'Restaurace U Černého orla',
    'Ostrava',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    49.8337,
    18.2793,
    'https://www.ucerneho-orla.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'sushi-point',
    'Sushi Point',
    'Ostrava',
    '🌿 PURE',
    'asijská / sushi',
    'Čerstvé sushi a asijská kuchyně.',
    49.8376,
    18.2861,
    'https://www.sushipoint-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-výčep',
    'Restaurace Výčep',
    'Ostrava',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Moderní pivnice s českou klasikou.',
    49.8354,
    18.2825,
    'https://www.vycep-ostrava.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-30 Opava
  (
    'restaurace-merlin',
    'Restaurace Merlin',
    'Opava',
    '🍷 LUXE',
    'fine dining / česká moderní',
    'Nejlepší restaurace v Opavě, moderní česká kuchyně.',
    49.9384,
    17.9024,
    'https://www.merlin-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Opava',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Opavy.',
    49.9391,
    17.9038,
    'https://www.ukata-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-rotta',
    'Pivnice U Rotta',
    'Opava',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice s českou klasikou.',
    49.9397,
    17.9045,
    'https://www.urotta.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-opava',
    'Pizzeria Venezia',
    'Opava',
    '🌿 PURE',
    'italská / pizza',
    'Autentická italská pizza v Opavě.',
    49.9388,
    17.9031,
    'https://www.venezia-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zamecká',
    'Restaurace Zámecká',
    'Opava',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v historickém centru.',
    49.9394,
    17.9041,
    'https://www.zamecka-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia',
    'Restaurace Slavia',
    'Opava',
    '🌊 CALM',
    'česká / mezinárodní',
    'Tradiční restaurace s českou kuchyní.',
    49.9401,
    17.9052,
    'https://www.slavia-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-dakota',
    'Steakhouse Dakota',
    'Opava',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v Opavě.',
    49.9385,
    17.9027,
    'https://www.dakota-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-dvou-koček',
    'Restaurace U Dvou koček',
    'Opava',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru.',
    49.9392,
    17.9035,
    'https://www.udvoukotek-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-evropa',
    'Kavárna Evropa',
    'Opava',
    '🌊 CALM',
    'kavárna / dezerty',
    'Historická kavárna na náměstí.',
    49.9398,
    17.9048,
    'https://www.evropa-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-factory-opava',
    'Burger Factory',
    'Opava',
    '🔥 DRAMA',
    'burger / fast casual',
    'Oblíbený burger bar.',
    49.9389,
    17.9033,
    'https://www.burgerfactory-opava.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 31-40 Frýdek-Místek
  (
    'restaurace-stará-radnice',
    'Restaurace Stará radnice',
    'Frýdek-Místek',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v historické budově.',
    49.6851,
    18.3489,
    'https://www.stararadnice-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda',
    'Restaurace Beseda',
    'Frýdek-Místek',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    49.6867,
    18.3512,
    'https://www.beseda-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-la-stella',
    'Pizzeria La Stella',
    'Frýdek-Místek',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie ve Frýdku-Místku.',
    49.6873,
    18.3523,
    'https://www.lastella-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-jakuba',
    'Pivnice U Jakuba',
    'Frýdek-Místek',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice s českou klasikou.',
    49.6858,
    18.3495,
    'https://www.ujakuba-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurant-imperial-fm',
    'Restaurant Imperial',
    'Frýdek-Místek',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Hotelová restaurace s kvalitní kuchyní.',
    49.6879,
    18.3534,
    'https://www.imperial-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kašny',
    'Restaurace U Kašny',
    'Frýdek-Místek',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    49.6862,
    18.3501,
    'https://www.ukasny-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-montana-fm',
    'Steakhouse Montana',
    'Frýdek-Místek',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky ve Frýdku-Místku.',
    49.6869,
    18.3517,
    'https://www.montana-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-saloon',
    'Restaurace Saloon',
    'Frýdek-Místek',
    '🔥 DRAMA',
    'americká / grill',
    'Americká restaurace s grilem.',
    49.6875,
    18.3529,
    'https://www.saloon-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-restaurant-golden',
    'Asia Restaurant Golden',
    'Frýdek-Místek',
    '🌿 PURE',
    'asijská / čínská',
    'Asijská kuchyně ve Frýdku-Místku.',
    49.6865,
    18.3506,
    'https://www.golden-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-retro',
    'Kavárna Retro',
    'Frýdek-Místek',
    '🌊 CALM',
    'kavárna / dezerty',
    'Retro kavárna s domácími dezerty.',
    49.6871,
    18.3520,
    'https://www.retro-fm.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 41-50 Karviná, Havířov
  (
    'restaurace-u-kocoura',
    'Restaurace U Kocoura',
    'Karviná',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Karviné.',
    49.8541,
    18.5412,
    'https://www.ukocoura-karvina.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-toscana',
    'Pizzeria Toscana',
    'Karviná',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Karviné.',
    49.8556,
    18.5434,
    'https://www.toscana-karvina.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-barbakan',
    'Pivnice Barbakan',
    'Karviná',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice s českou klasikou.',
    49.8548,
    18.5423,
    'https://www.barbakan-karvina.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slovan',
    'Restaurace Slovan',
    'Karviná',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    49.8562,
    18.5445,
    'https://www.slovan-karvina.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-corso',
    'Restaurace Corso',
    'Karviná',
    '🌊 CALM',
    'česká / mezinárodní',
    'Restaurace s českou a mezinárodní kuchyní.',
    49.8553,
    18.5429,
    'https://www.corso-karvina.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-havirov',
    'Restaurace U Radnice',
    'Havířov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Havířově.',
    49.7791,
    18.4367,
    'https://www.uradnice-havirov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-havirov',
    'Pizzeria Venezia',
    'Havířov',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Havířově.',
    49.7804,
    18.4389,
    'https://www.venezia-havirov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-sport-havirov',
    'Restaurace Sport',
    'Havířov',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v Havířově.',
    49.7798,
    18.4378,
    'https://www.sport-havirov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-bar-havirov',
    'Burger Bar',
    'Havířov',
    '🔥 DRAMA',
    'burger / fast casual',
    'Burger bar v Havířově.',
    49.7810,
    18.4395,
    'https://www.burgerbar-havirov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-bistro-havirov',
    'Asia Bistro',
    'Havířov',
    '🌿 PURE',
    'asijská / čínská',
    'Asijská kuchyně v Havířově.',
    49.7801,
    18.4384,
    'https://www.asiabistro-havirov.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 51-60 Třinec, Nový Jičín
  (
    'restaurace-beskyd',
    'Restaurace Beskyd',
    'Třinec',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Třinci.',
    49.6778,
    18.6712,
    'https://www.beskyd-trinec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-la-piazza',
    'Pizzeria La Piazza',
    'Třinec',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Třinci.',
    49.6789,
    18.6734,
    'https://www.lapiazza-trinec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-jelena',
    'Pivnice U Jelena',
    'Třinec',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice v Třinci.',
    49.6784,
    18.6723,
    'https://www.ujelena-trinec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-imperial-trinec',
    'Restaurace Imperial',
    'Třinec',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Hotelová restaurace v Třinci.',
    49.6795,
    18.6745,
    'https://www.imperial-trinec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-sport-trinec',
    'Restaurace Sport',
    'Třinec',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace u hokejové haly.',
    49.6781,
    18.6718,
    'https://www.sport-trinec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-old-inn',
    'Restaurace Old Inn',
    'Nový Jičín',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Nejlepší restaurace v Novém Jičíně.',
    49.5945,
    18.0101,
    'https://www.oldinn.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-nj',
    'Restaurace U Radnice',
    'Nový Jičín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí.',
    49.5956,
    18.0123,
    'https://www.uradnice-nj.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-sicilia',
    'Pizzeria Sicilia',
    'Nový Jičín',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Novém Jičíně.',
    49.5951,
    18.0112,
    'https://www.sicilia-nj.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-ševce',
    'Pivnice U Ševce',
    'Nový Jičín',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice v Novém Jičíně.',
    49.5948,
    18.0106,
    'https://www.usevce-nj.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia-nj',
    'Restaurace Slavia',
    'Nový Jičín',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    49.5962,
    18.0134,
    'https://www.slavia-nj.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 61-70 Český Těšín, Kopřivnice
  (
    'restaurace-piast',
    'Restaurace Piast',
    'Český Těšín',
    '🌊 CALM',
    'česká / polská',
    'Restaurace s českou a polskou kuchyní.',
    49.7461,
    18.6256,
    'https://www.piast.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-bella-vista',
    'Pizzeria Bella Vista',
    'Český Těšín',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Českém Těšíně.',
    49.7473,
    18.6278,
    'https://www.bellavista-ct.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-mostu',
    'Restaurace U Mostu',
    'Český Těšín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace u mostu přes Olši.',
    49.7467,
    18.6267,
    'https://www.umostu-ct.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-granát',
    'Pivnice Granát',
    'Český Těšín',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice v Českém Těšíně.',
    49.7478,
    18.6289,
    'https://www.granat-ct.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-tesla',
    'Restaurace Tesla',
    'Český Těšín',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    49.7470,
    18.6273,
    'https://www.tesla-ct.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-tatra',
    'Restaurace Tatra',
    'Kopřivnice',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Kopřivnici.',
    49.5989,
    18.1445,
    'https://www.tatra-koprivnice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-roma-koprivnice',
    'Pizzeria Roma',
    'Kopřivnice',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Kopřivnici.',
    49.5998,
    18.1467,
    'https://www.roma-koprivnice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-koprivnice',
    'Restaurace U Radnice',
    'Kopřivnice',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace na náměstí.',
    49.5994,
    18.1456,
    'https://www.uradnice-koprivnice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-řezníka',
    'Pivnice U Řezníka',
    'Kopřivnice',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Pivnice s českou klasikou.',
    49.6003,
    18.1478,
    'https://www.ureznika-koprivnice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-sport-koprivnice',
    'Restaurace Sport',
    'Kopřivnice',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace u sportovního areálu.',
    49.5991,
    18.1450,
    'https://www.sport-koprivnice.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 71-80 Menší města
  (
    'restaurace-orlová',
    'Restaurace Orlová',
    'Orlová',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Orlové.',
    49.8456,
    18.4312,
    'https://www.restaurace-orlova.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-napoli-orlova',
    'Pizzeria Napoli',
    'Orlová',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Orlové.',
    49.8467,
    18.4334,
    'https://www.napoli-orlova.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-bruntál',
    'Restaurace Bruntál',
    'Bruntál',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Bruntále.',
    49.9881,
    17.4645,
    'https://www.restaurace-bruntal.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-italia-bruntal',
    'Pizzeria Italia',
    'Bruntál',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Bruntále.',
    49.9893,
    17.4667,
    'https://www.italia-bruntal.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-jeseník',
    'Restaurace Jeseník',
    'Jeseník',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Jeseníku.',
    50.2289,
    17.2045,
    'https://www.restaurace-jesenik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-jesenik',
    'Pizzeria Venezia',
    'Jeseník',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Jeseníku.',
    50.2301,
    17.2067,
    'https://www.venezia-jesenik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-krnov',
    'Restaurace Krnov',
    'Krnov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Krnově.',
    50.0896,
    17.7034,
    'https://www.restaurace-krnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-roma-krnov',
    'Pizzeria Roma',
    'Krnov',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Krnově.',
    50.0908,
    17.7056,
    'https://www.roma-krnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-bohumín',
    'Restaurace Bohumín',
    'Bohumín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Bohumíně.',
    49.9034,
    18.3578,
    'https://www.restaurace-bohumin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-bella-bohumin',
    'Pizzeria Bella',
    'Bohumín',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Bohumíně.',
    49.9047,
    18.3601,
    'https://www.bella-bohumin.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
