-- Import restaurací LIBERECKÝ KRAJ 1–50 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10 Liberec (krajské město)
  (
    'restaurant-radnice',
    'Restaurant Radnice',
    'Liberec',
    '🍷 LUXE',
    'fine dining / česká moderní',
    'Nejlepší fine dining v Liberci, moderní česká kuchyně.',
    50.7671,
    15.0562,
    'https://www.radnice-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-bile-kamenice',
    'Restaurace U Bílé kamenice',
    'Liberec',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace v centru Liberce.',
    50.7684,
    15.0578,
    'https://www.ubilekamenice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivovar-konrad',
    'Pivovar Konrad',
    'Liberec',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Minipivovar s vlastním pivem a českou klasikou.',
    50.7692,
    15.0589,
    'https://www.konrad.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-hotel-imperial',
    'Restaurace Hotel Imperial',
    'Liberec',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Luxusní hotelová restaurace v historickém hotelu.',
    50.7678,
    15.0571,
    'https://www.imperial-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-il-forno',
    'Pizzeria Il Forno',
    'Liberec',
    '🌿 PURE',
    'italská / pizza',
    'Autentická italská pizza z pece.',
    50.7697,
    15.0601,
    'https://www.ilforno-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlateho-lva',
    'Restaurace U Zlatého lva',
    'Liberec',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace v Liberci.',
    50.7687,
    15.0584,
    'https://www.uzlateho-lva.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-texas',
    'Steakhouse Texas',
    'Liberec',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v americkém stylu.',
    50.7702,
    15.0612,
    'https://www.texas-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda',
    'Restaurace Beseda',
    'Liberec',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.7681,
    15.0574,
    'https://www.beseda-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-restaurant-bamboo',
    'Asia Restaurant Bamboo',
    'Liberec',
    '🌿 PURE',
    'asijská / čínská',
    'Asijská kuchyně v Liberci.',
    50.7705,
    15.0623,
    'https://www.bamboo-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-azyl',
    'Kavárna Azyl',
    'Liberec',
    '🌊 CALM',
    'kavárna / vegetariánská',
    'Alternativní kavárna s vegetariánskou kuchyní.',
    50.7689,
    15.0587,
    'https://www.azyl-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20 Liberec pokračování
  (
    'restaurace-u-ceske-koruny',
    'Restaurace U České koruny',
    'Liberec',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Liberci.',
    50.7694,
    15.0595,
    'https://www.uceskekoruny.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-bar-liberec',
    'Burger Bar',
    'Liberec',
    '🔥 DRAMA',
    'burger / fast casual',
    'Oblíbený burger bar v Liberci.',
    50.7708,
    15.0629,
    'https://www.burgerbar-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-vratislavsky-dum',
    'Restaurace Vratislavský dům',
    'Liberec',
    '🌊 CALM',
    'česká / mezinárodní',
    'Restaurace v historické budově.',
    50.7685,
    15.0579,
    'https://www.vratislavsky.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-sklep',
    'Restaurace Sklep',
    'Liberec',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Pivnice ve sklepě s českou klasikou.',
    50.7690,
    15.0590,
    'https://www.sklep-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'sushi-bar-sakura',
    'Sushi Bar Sakura',
    'Liberec',
    '🌿 PURE',
    'asijská / sushi',
    'Čerstvé sushi v Liberci.',
    50.7699,
    15.0606,
    'https://www.sakura-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-jested',
    'Restaurace Ještěd',
    'Liberec - Ještěd',
    '🍷 LUXE',
    'fine dining / vyhlídková',
    'Ikonická restaurace na vrcholu Ještědu, unikátní výhled.',
    50.7314,
    15.0123,
    'https://www.jested.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-liberec',
    'Pizzeria Venezia',
    'Liberec',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Liberci.',
    50.7703,
    15.0617,
    'https://www.venezia-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-vysluni',
    'Restaurace Na Výsluní',
    'Liberec',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v Liberci.',
    50.7693,
    15.0593,
    'https://www.navysluni-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-cokolada',
    'Kavárna Čokoláda',
    'Liberec',
    '🌊 CALM',
    'kavárna / dezerty',
    'Kavárna s domácími dezerty.',
    50.7686,
    15.0581,
    'https://www.cokolada-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-schnellu',
    'Restaurace U Schnellů',
    'Liberec',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.7695,
    15.0598,
    'https://www.uschnellu-liberec.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-30 Jablonec nad Nisou
  (
    'restaurant-bohemia',
    'Restaurant Bohemia',
    'Jablonec nad Nisou',
    '🍷 LUXE',
    'fine dining / česká moderní',
    'Nejlepší restaurace v Jablonci, moderní česká kuchyně.',
    50.7234,
    15.1712,
    'https://www.bohemia-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-namesti',
    'Restaurace U Náměstí',
    'Jablonec nad Nisou',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Jablonce.',
    50.7245,
    15.1734,
    'https://www.unamesti-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-kocoura',
    'Pivnice U Kocoura',
    'Jablonec nad Nisou',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice s českou klasikou.',
    50.7251,
    15.1745,
    'https://www.ukocoura-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-napoli',
    'Pizzeria Napoli',
    'Jablonec nad Nisou',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Jablonci.',
    50.7240,
    15.1728,
    'https://www.napoli-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia',
    'Restaurace Slavia',
    'Jablonec nad Nisou',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.7256,
    15.1756,
    'https://www.slavia-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-montana',
    'Steakhouse Montana',
    'Jablonec nad Nisou',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v Jablonci.',
    50.7248,
    15.1739,
    'https://www.montana-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Jablonec nad Nisou',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Jablonci.',
    50.7243,
    15.1731,
    'https://www.ukata-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-bistro-jablonec',
    'Asia Bistro',
    'Jablonec nad Nisou',
    '🌿 PURE',
    'asijská / čínská',
    'Asijská kuchyně v Jablonci.',
    50.7253,
    15.1750,
    'https://www.asiabistro-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-imperial',
    'Restaurace Imperial',
    'Jablonec nad Nisou',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Hotelová restaurace v centru města.',
    50.7246,
    15.1736,
    'https://www.imperial-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-factory',
    'Burger Factory',
    'Jablonec nad Nisou',
    '🔥 DRAMA',
    'burger / fast casual',
    'Oblíbený burger bar.',
    50.7249,
    15.1742,
    'https://www.burgerfactory-jablonec.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 31-38 Česká Lípa
  (
    'restaurace-u-radnice',
    'Restaurace U Radnice',
    'Česká Lípa',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí.',
    50.6856,
    14.5378,
    'https://www.uradnice-cl.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivovar-cvikov',
    'Pivovar Cvikov',
    'Česká Lípa',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Minipivovar s českou klasikou.',
    50.6867,
    14.5401,
    'https://www.pivovarcvikov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-roma',
    'Pizzeria Roma',
    'Česká Lípa',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v České Lípě.',
    50.6862,
    14.5389,
    'https://www.roma-cl.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-sport',
    'Restaurace Sport',
    'Česká Lípa',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace u sportovního areálu.',
    50.6873,
    14.5412,
    'https://www.sport-cl.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda',
    'Restaurace Beseda',
    'Česká Lípa',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.6859,
    14.5384,
    'https://www.beseda-cl.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-texas-cl',
    'Steakhouse Texas',
    'Česká Lípa',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v České Lípě.',
    50.6869,
    14.5395,
    'https://www.texas-cl.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-lva',
    'Restaurace U Lva',
    'Česká Lípa',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.6865,
    14.5392,
    'https://www.ulva-cl.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-retro',
    'Kavárna Retro',
    'Česká Lípa',
    '🌊 CALM',
    'kavárna / dezerty',
    'Retro kavárna s domácími dezerty.',
    50.6858,
    14.5380,
    'https://www.retro-cl.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 39-44 Semily
  (
    'restaurace-u-semilska',
    'Restaurace U Semilska',
    'Semily',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Semilech.',
    50.6012,
    15.3356,
    'https://www.usemilska.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-la-stella',
    'Pizzeria La Stella',
    'Semily',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Semilech.',
    50.6023,
    15.3378,
    'https://www.lastella-semily.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-kocoura',
    'Pivnice U Kocoura',
    'Semily',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice v Semilech.',
    50.6018,
    15.3367,
    'https://www.ukocoura-semily.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-sport',
    'Restaurace Sport',
    'Semily',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace u sportovního areálu.',
    50.6028,
    15.3389,
    'https://www.sport-semily.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice',
    'Restaurace U Radnice',
    'Semily',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.6015,
    15.3361,
    'https://www.uradnice-semily.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-bar-semily',
    'Burger Bar',
    'Semily',
    '🔥 DRAMA',
    'burger / fast casual',
    'Burger bar v Semilech.',
    50.6021,
    15.3373,
    'https://www.burgerbar-semily.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 45-50 Turnov a okolí
  (
    'restaurace-u-zlate-podkovy',
    'Restaurace U Zlaté podkovy',
    'Turnov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Turnově.',
    50.5834,
    15.1545,
    'https://www.uzlatepodkovy.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-sicilia',
    'Pizzeria Sicilia',
    'Turnov',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Turnově.',
    50.5845,
    15.1567,
    'https://www.sicilia-turnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-ceske-koruny',
    'Restaurace U České koruny',
    'Turnov',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru města.',
    50.5839,
    15.1556,
    'https://www.uceskekoruny-turnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-tanvald',
    'Restaurace Tanvald',
    'Tanvald',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Tanvaldu.',
    50.7356,
    15.3123,
    'https://www.restaurace-tanvald.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zelezny-brod',
    'Restaurace Železný Brod',
    'Železný Brod',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace ve městě skla.',
    50.6434,
    15.2556,
    'https://www.restaurace-zb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-frydlant',
    'Restaurace Frýdlant',
    'Frýdlant',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace ve Frýdlantu.',
    50.9223,
    15.0789,
    'https://www.restaurace-frydlant.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
