-- Import restaurací ZLÍNSKÝ KRAJ 1–60 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10 Zlín (krajské město)
  (
    'restaurant-mosquito',
    'Restaurant Mosquito',
    'Zlín',
    '🍷 LUXE',
    'fine dining / moderní česká',
    'Nejlepší fine dining ve Zlíně, moderní česká kuchyně.',
    49.2266,
    17.6667,
    'https://www.mosquito-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice',
    'Restaurace U Radnice',
    'Zlín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Zlína.',
    49.2277,
    17.6689,
    'https://www.uradnice-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivovar-zirafka',
    'Pivovar Žirafka',
    'Zlín',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Oblíbený minipivovar ve Zlíně.',
    49.2283,
    17.6701,
    'https://www.zirafka.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-myslivna',
    'Restaurace Myslivna',
    'Zlín',
    '🍷 LUXE',
    'fine dining / zvěřina',
    'Luxusní restaurace se zaměřením na zvěřinu.',
    49.2272,
    17.6678,
    'https://www.myslivna-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-la-fontana',
    'Pizzeria La Fontana',
    'Zlín',
    '🌿 PURE',
    'italská / pizza',
    'Autentická italská pizza ve Zlíně.',
    49.2288,
    17.6712,
    'https://www.lafontana-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Zlín',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    49.2275,
    17.6684,
    'https://www.ukata-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-western',
    'Steakhouse Western',
    'Zlín',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v americkém stylu.',
    49.2293,
    17.6723,
    'https://www.western-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia',
    'Restaurace Slavia',
    'Zlín',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    49.2270,
    17.6673,
    'https://www.slavia-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'sushi-bar-sakura',
    'Sushi Bar Sakura',
    'Zlín',
    '🌿 PURE',
    'asijská / sushi',
    'Čerstvé sushi ve Zlíně.',
    49.2298,
    17.6734,
    'https://www.sakura-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-14',
    'Kavárna 14',
    'Zlín',
    '🌊 CALM',
    'kavárna / dezerty',
    'Moderní kavárna ve funkcionalistické architektuře.',
    49.2280,
    17.6695,
    'https://www.kavarna14.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20 Zlín pokračování
  (
    'restaurace-zlatá-bašta',
    'Restaurace Zlatá bašta',
    'Zlín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace ve Zlíně.',
    49.2285,
    17.6706,
    'https://www.zlatbasta.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-inn',
    'Burger Inn',
    'Zlín',
    '🔥 DRAMA',
    'burger / fast casual',
    'Oblíbený burger bar ve Zlíně.',
    49.2301,
    17.6745,
    'https://www.burgerinn-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda',
    'Restaurace Beseda',
    'Zlín',
    '🌊 CALM',
    'česká / mezinárodní',
    'Restaurace v kulturním domě.',
    49.2268,
    17.6670,
    'https://www.beseda-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-kocoura',
    'Pivnice U Kocoura',
    'Zlín',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Pivnice s českou klasikou.',
    49.2290,
    17.6717,
    'https://www.ukocoura-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-semináře',
    'Restaurace U Semináře',
    'Zlín',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    49.2274,
    17.6681,
    'https://www.useminare-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurant-interhotel',
    'Restaurant Interhotel',
    'Zlín',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Luxusní hotelová restaurace.',
    49.2267,
    17.6668,
    'https://www.interhotel-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia',
    'Pizzeria Venezia',
    'Zlín',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie ve Zlíně.',
    49.2295,
    17.6728,
    'https://www.venezia-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-anděla',
    'Restaurace U Anděla',
    'Zlín',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru.',
    49.2281,
    17.6698,
    'https://www.uandela-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-restaurant-bamboo',
    'Asia Restaurant Bamboo',
    'Zlín',
    '🌿 PURE',
    'asijská / čínská',
    'Asijská kuchyně ve Zlíně.',
    49.2303,
    17.6750,
    'https://www.bamboo-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-dvou-kohoutků',
    'Restaurace U Dvou kohoutků',
    'Zlín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    49.2271,
    17.6675,
    'https://www.udvoukohoutu.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-25 Zlín dokončení
  (
    'kavárna-baťa',
    'Kavárna Baťa',
    'Zlín',
    '🌊 CALM',
    'kavárna / historická',
    'Historická kavárna v centru Zlína.',
    49.2279,
    17.6692,
    'https://www.kavarnabata.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zámek-lešná',
    'Restaurace Zámek Lešná',
    'Zlín - Lešná',
    '🍷 LUXE',
    'fine dining / zámecká',
    'Luxusní zámecká restaurace u ZOO.',
    49.2456,
    17.7134,
    'https://www.zameklesna.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'grill-house',
    'Grill House',
    'Zlín',
    '🔥 DRAMA',
    'grill / steakhouse',
    'Grilované speciality ve Zlíně.',
    49.2286,
    17.6709,
    'https://www.grillhouse-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-třech-lip',
    'Restaurace U Tří lip',
    'Zlín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace ve Zlíně.',
    49.2273,
    17.6679,
    'https://www.utrilip.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'bistro-21',
    'Bistro 21',
    'Zlín',
    '🌿 PURE',
    'moderní / healthy',
    'Moderní bistro s healthy kuchyní.',
    49.2291,
    17.6720,
    'https://www.bistro21-zlin.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 26-37 Kroměříž
  (
    'restaurace-černý-orel',
    'Restaurace Černý orel',
    'Kroměříž',
    '🍷 LUXE',
    'fine dining / česká moderní',
    'Nejlepší restaurace v Kroměříži, moderní česká kuchyně.',
    49.2978,
    17.3934,
    'https://www.cernyorel-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-km',
    'Restaurace U Radnice',
    'Kroměříž',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí v Kroměříži.',
    49.2989,
    17.3956,
    'https://www.uradnice-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivovar-černý-orel',
    'Pivovar Černý orel',
    'Kroměříž',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Minipivovar s vlastním pivem.',
    49.2995,
    17.3967,
    'https://www.pivovar-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-grosseto-km',
    'Pizzeria Grosseto',
    'Kroměříž',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Kroměříži.',
    49.2983,
    17.3945,
    'https://www.grosseto-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia-km',
    'Restaurace Slavia',
    'Kroměříž',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    49.3001,
    17.3978,
    'https://www.slavia-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zámek-kroměříž',
    'Restaurace Zámek Kroměříž',
    'Kroměříž',
    '🍷 LUXE',
    'fine dining / historická',
    'Luxusní restaurace v UNESCO zámku.',
    49.2985,
    17.3950,
    'https://www.zamekkm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-texas-km',
    'Steakhouse Texas',
    'Kroměříž',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v Kroměříži.',
    49.2991,
    17.3961,
    'https://www.texas-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata-km',
    'Restaurace U Kata',
    'Kroměříž',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Kroměříži.',
    49.2987,
    17.3953,
    'https://www.ukata-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-bistro-km',
    'Asia Bistro',
    'Kroměříž',
    '🌿 PURE',
    'asijská / čínská',
    'Asijská kuchyně v Kroměříži.',
    49.2997,
    17.3972,
    'https://www.asiabistro-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-podzámecká',
    'Kavárna Podzámecká',
    'Kroměříž',
    '🌊 CALM',
    'kavárna / dezerty',
    'Kavárna u Podzámecké zahrady.',
    49.2981,
    17.3942,
    'https://www.podzamecka-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-bar-km',
    'Burger Bar',
    'Kroměříž',
    '🔥 DRAMA',
    'burger / fast casual',
    'Burger bar v Kroměříži.',
    49.2993,
    17.3964,
    'https://www.burgerbar-km.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda-km',
    'Restaurace Beseda',
    'Kroměříž',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v Kroměříži.',
    49.2988,
    17.3955,
    'https://www.beseda-km.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 38-47 Uherské Hradiště
  (
    'restaurace-grand',
    'Restaurace Grand',
    'Uherské Hradiště',
    '🍷 LUXE',
    'fine dining / česká moderní',
    'Nejlepší fine dining v Uherském Hradišti.',
    49.0697,
    17.4589,
    'https://www.grand-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-uh',
    'Restaurace U Radnice',
    'Uherské Hradiště',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí.',
    49.0708,
    17.4612,
    'https://www.uradnice-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-u-vináře',
    'Vinárna U Vináře',
    'Uherské Hradiště',
    '🍷 LUXE',
    'vinárna / moravská',
    'Vinárna s moravskou kuchyní a vínem.',
    49.0714,
    17.4623,
    'https://www.uvinare-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-uh',
    'Pizzeria Venezia',
    'Uherské Hradiště',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Uherském Hradišti.',
    49.0703,
    17.4601,
    'https://www.venezia-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia-uh',
    'Restaurace Slavia',
    'Uherské Hradiště',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    49.0719,
    17.4634,
    'https://www.slavia-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-montana-uh',
    'Steakhouse Montana',
    'Uherské Hradiště',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v Uherském Hradišti.',
    49.0711,
    17.4618,
    'https://www.montana-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata-uh',
    'Restaurace U Kata',
    'Uherské Hradiště',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru.',
    49.0706,
    17.4607,
    'https://www.ukata-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-hanácká-uh',
    'Pivnice Hanácká',
    'Uherské Hradiště',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice s českou klasikou.',
    49.0716,
    17.4628,
    'https://www.hanacka-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'sushi-bar-uh',
    'Sushi Bar',
    'Uherské Hradiště',
    '🌿 PURE',
    'asijská / sushi',
    'Čerstvé sushi v Uherském Hradišti.',
    49.0709,
    17.4614,
    'https://www.sushibar-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-trio',
    'Kavárna Trio',
    'Uherské Hradiště',
    '🌊 CALM',
    'kavárna / dezerty',
    'Moderní kavárna v centru města.',
    49.0701,
    17.4595,
    'https://www.trio-uh.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 48-55 Vsetín a Valašsko
  (
    'restaurace-vsacký-dvůr',
    'Restaurace Vsacký dvůr',
    'Vsetín',
    '🌊 CALM',
    'valašská / česká',
    'Tradiční valašská restaurace.',
    49.3389,
    17.9967,
    'https://www.vsackydvur.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-vsetin',
    'Restaurace U Radnice',
    'Vsetín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace ve Vsetíně.',
    49.3401,
    17.9989,
    'https://www.uradnice-vsetin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-roma-vsetin',
    'Pizzeria Roma',
    'Vsetín',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie ve Vsetíně.',
    49.3395,
    17.9978,
    'https://www.roma-vsetin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-valašská-bašta',
    'Restaurace Valašská bašta',
    'Vsetín',
    '🌊 CALM',
    'valašská / regionální',
    'Valašské speciality a regionální kuchyně.',
    49.3407,
    18.0001,
    'https://www.valaskabasta.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-vsetin',
    'Steakhouse Vsetín',
    'Vsetín',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky ve Vsetíně.',
    49.3398,
    17.9983,
    'https://www.steakhouse-vsetin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-rožnov',
    'Restaurace Rožnov',
    'Rožnov pod Radhoštěm',
    '🌊 CALM',
    'valašská / česká',
    'Tradiční valašská restaurace v Rožnově.',
    49.4589,
    18.1434,
    'https://www.restaurace-roznov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-wallachian-open-air-museum',
    'Restaurace Valašské muzeum',
    'Rožnov pod Radhoštěm',
    '🌊 CALM',
    'valašská / tradiční',
    'Valašská restaurace v areálu skanzenu.',
    49.4612,
    18.1456,
    'https://www.vmp.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-roznov',
    'Pizzeria Venezia',
    'Rožnov pod Radhoštěm',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Rožnově.',
    49.4595,
    18.1445,
    'https://www.venezia-roznov.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 56-60 Ostatní města
  (
    'restaurace-otrokovice',
    'Restaurace Otrokovice',
    'Otrokovice',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Otrokovicích.',
    49.2095,
    17.5389,
    'https://www.restaurace-otrokovice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-napoli-otrokovice',
    'Pizzeria Napoli',
    'Otrokovice',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Otrokovicích.',
    49.2106,
    17.5412,
    'https://www.napoli-otrokovice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-valašské-meziříčí',
    'Restaurace Valašské Meziříčí',
    'Valašské Meziříčí',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace ve Valašském Meziříčí.',
    49.4718,
    17.9712,
    'https://www.restaurace-vm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavičín',
    'Restaurace Slavičín',
    'Slavičín',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace ve Slavičíně.',
    49.0878,
    17.8734,
    'https://www.restaurace-slavicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-luhačovice',
    'Restaurace Luhačovice',
    'Luhačovice',
    '🍷 LUXE',
    'lázeňská / česká moderní',
    'Luxusní lázeňská restaurace v Luhačovicích.',
    49.0995,
    17.7567,
    'https://www.restaurace-luhacovice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-vizovice',
    'Restaurace Vizovice',
    'Vizovice',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace ve Vizovicích (město slivovice).',
    49.2223,
    17.8523,
    'https://www.restaurace-vizovice.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
