-- Import restaurací JIHOMORAVSKÝ KRAJ 1–80 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10
  (
    'restaurant-pavillon',
    'Restaurant Pavillon',
    'Brno',
    '🍷 LUXE',
    'fine dining / moderní evropská',
    'Nejvýznamnější fine-dining adresa v Brně, Michelinská úroveň.',
    49.1951,
    16.6068,
    'https://www.pavillon.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-tří-korunek',
    'Restaurace U Tří korunek',
    'Brno',
    '🌊 CALM',
    'česká kuchyně',
    'Historická restaurace v centru Brna, česká klasika.',
    49.1925,
    16.6085,
    'https://www.utrikorunek.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-cerneho-medvěda-brno',
    'Restaurace U Černého medvěda',
    'Brno',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční brněnská restaurace s dlouhou historií.',
    49.1929,
    16.6081,
    'https://www.ucernehomeveda-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-stopkova',
    'Restaurace Stopkova',
    'Brno',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Pivovarnická restaurace s vlastním pivem, živá atmosféra.',
    49.1933,
    16.6077,
    'https://www.stopkova.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-royal-ribs',
    'Restaurace Royal Ribs',
    'Brno',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Výborné steaky a žebírka, dramatická atmosphere.',
    49.1937,
    16.6073,
    'https://www.royalribs.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-borgo-agnese',
    'Restaurace Borgo Agnese',
    'Brno',
    '🍷 LUXE',
    'italská kuchyně / fine dining',
    'Luxusní italská restaurace s vynikající gastronomií.',
    49.1921,
    16.6089,
    'https://www.borgoagnese.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-labužník',
    'Restaurace Labužník',
    'Brno',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Oblíbená restaurace s kvalitní kuchyní a příjemnou atmosférou.',
    49.1917,
    16.6093,
    'https://www.labuznik.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-u-broučka',
    'Vinárna U Broučka',
    'Brno',
    '🌿 PURE',
    'vinařská kuchyně',
    'Tradiční vinárna s moravskými víny a regionální kuchyní.',
    49.1913,
    16.6097,
    'https://www.ubroucka.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-pegas',
    'Pivnice Pegas',
    'Brno',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Legendární brněnský minipivovar s živou atmosférou.',
    49.1909,
    16.6101,
    'https://www.pegas.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-soul-bistro',
    'Restaurace Soul Bistro',
    'Brno',
    '🌿 PURE',
    'moderní evropská / healthy',
    'Moderní bistro s důrazem na kvalitní suroviny.',
    49.1941,
    16.6069,
    'https://www.soulbistro.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20
  (
    'restaurace-koishi',
    'Restaurace Koishi',
    'Brno',
    '🍷 LUXE',
    'japonská / sushi',
    'Prémiová japonská restaurace s autentickou kuchyní.',
    49.1945,
    16.6065,
    'https://www.koishi.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-königů',
    'Restaurace U Königů',
    'Brno',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace s českou kuchyní a klidnou atmosférou.',
    49.1905,
    16.6105,
    'https://www.ukonigu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-špalíček',
    'Restaurace Špalíček',
    'Brno',
    '🌊 CALM',
    'česká / moravská kuchyně',
    'Restaurace v historickém centru, moravské speciality.',
    49.1949,
    16.6061,
    'https://www.spalicek-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-u-rady',
    'Vinárna U Rady',
    'Brno',
    '🌿 PURE',
    'vinařská kuchyně',
    'Stylová vinárna s výběrem moravských vín.',
    49.1953,
    16.6057,
    'https://www.urady.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-hotel-international',
    'Restaurace Hotel International',
    'Brno',
    '🍷 LUXE',
    'moderní evropská',
    'Luxusní hotelová restaurace s kvalitní gastronomií.',
    49.1901,
    16.6109,
    'https://www.international-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-richarda',
    'Pivnice U Richarda',
    'Brno',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená hospoda s živou atmosférou a dobrým pivem.',
    49.1957,
    16.6053,
    'https://www.uricharda.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-starém-brně',
    'Restaurace Na starém Brně',
    'Brno',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace se spolehlivou českou kuchyní.',
    49.1961,
    16.6049,
    'https://www.nastarembrne.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zebra',
    'Restaurace Zebra',
    'Brno',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Stylový steakhouse s kvalitním masem.',
    49.1897,
    16.6113,
    'https://www.zebra-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-pod-radnicí',
    'Vinárna Pod radnicí',
    'Brno',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna ve sklepních prostorách, moravská vína.',
    49.1965,
    16.6045,
    'https://www.podradnici-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-ševce',
    'Restaurace U Ševce',
    'Brno',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    49.1893,
    16.6117,
    'https://www.usevce-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-30
  (
    'restaurace-u-kocoura-znojmo',
    'Restaurace U Kocoura',
    'Znojmo',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Znojma, česká klasika.',
    48.8555,
    16.0488,
    'https://www.ukocoura-znojmo.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-věčnosti',
    'Restaurace Na věčnosti',
    'Znojmo',
    '🍷 LUXE',
    'moderní česká / vinařská',
    'Stylová restaurace s kvalitní gastronomií a víny.',
    48.8559,
    16.0484,
    'https://www.navecnosti.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-u-rytíře',
    'Vinárna U Rytíře',
    'Znojmo',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna s výběrem znojemských vín a regionální kuchyní.',
    48.8563,
    16.0480,
    'https://www.urytire-znojmo.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-černého-orla-znojmo',
    'Restaurace U Černého orla',
    'Znojmo',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace se spolehlivou českou kuchyní.',
    48.8551,
    16.0492,
    'https://www.ucernehoorla-znojmo.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-na-náměstí-znojmo',
    'Pivnice Na náměstí',
    'Znojmo',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    48.8567,
    16.0476,
    'https://www.nanamesti-znojmo.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-prestige-znojmo',
    'Restaurace Prestige',
    'Znojmo',
    '🍷 LUXE',
    'moderní evropská',
    'Hotelová restaurace s kvalitní kuchyní.',
    48.8547,
    16.0496,
    'https://www.prestige-znojmo.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-šobes-mikulov',
    'Vinárna Šobes',
    'Mikulov',
    '🍷 LUXE',
    'vinařská kuchyně / fine dining',
    'Exkluzivní vinařská restaurace, top adresa v Mikulově.',
    48.8059,
    16.6381,
    'https://www.sobes.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-templ-mikulov',
    'Restaurace Templ',
    'Mikulov',
    '🌊 CALM',
    'česká / moravská kuchyně',
    'Historická restaurace v centru města.',
    48.8063,
    16.6377,
    'https://www.templ-mikulov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-na-zámku',
    'Vinárna Na zámku',
    'Mikulov',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna na mikulovském zámku s výhledem.',
    48.8067,
    16.6373,
    'https://www.nazamku-mikulov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kapličky',
    'Restaurace U Kapličky',
    'Mikulov',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    48.8055,
    16.6385,
    'https://www.ukaplicky-mikulov.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 31-40
  (
    'vinárna-u-capa',
    'Vinárna U Čápa',
    'Mikulov',
    '🌿 PURE',
    'vinařská kuchyně',
    'Tradiční vinárna s moravskými víny.',
    48.8071,
    16.6369,
    'https://www.ucapa-mikulov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-golf-mikulov',
    'Restaurace Golf',
    'Mikulov',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Restaurace u golfového hřiště s krásným výhledem.',
    48.7989,
    16.6451,
    'https://www.golf-mikulov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-breclav',
    'Restaurace U Radnice',
    'Břeclav',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí, česká klasika.',
    48.7589,
    16.8823,
    'https://www.uradnice-breclav.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-zámek-breclav',
    'Restaurace Zámek',
    'Břeclav',
    '🍷 LUXE',
    'moderní česká',
    'Stylová restaurace na břeclavském zámku.',
    48.7593,
    16.8819,
    'https://www.zamek-breclav.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-pod-věží',
    'Vinárna Pod věží',
    'Břeclav',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna s moravskými víny a regionální kuchyní.',
    48.7597,
    16.8815,
    'https://www.podvezi-breclav.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-kocoura-breclav',
    'Pivnice U Kocoura',
    'Břeclav',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    48.7585,
    16.8827,
    'https://www.ukocoura-breclav.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-apollo-breclav',
    'Restaurace Apollo',
    'Břeclav',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní.',
    48.7601,
    16.8811,
    'https://www.apollo-breclav.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-černého-orla-hodonin',
    'Restaurace U Černého orla',
    'Hodonín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Hodonína.',
    48.8489,
    17.1325,
    'https://www.ucernehoorla-hodonin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-grand-hodonin',
    'Restaurace Grand',
    'Hodonín',
    '🍷 LUXE',
    'moderní česká',
    'Hotelová restaurace s kvalitní gastronomií.',
    48.8493,
    17.1321,
    'https://www.grand-hodonin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-u-anděla',
    'Vinárna U Anděla',
    'Hodonín',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna s moravskými víny a tradiční kuchyní.',
    48.8497,
    17.1317,
    'https://www.uandela-hodonin.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 41-50
  (
    'pivnice-na-náměstí-hodonin',
    'Pivnice Na náměstí',
    'Hodonín',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českým pivem.',
    48.8485,
    17.1329,
    'https://www.nanamesti-hodonin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-vyskov',
    'Restaurace U Radnice',
    'Vyškov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí, česká klasika.',
    49.2777,
    16.9989,
    'https://www.uradnice-vyskov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-grand-vyskov',
    'Restaurace Grand',
    'Vyškov',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní.',
    49.2781,
    16.9985,
    'https://www.grand-vyskov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-zeleného-stromu',
    'Pivnice U Zeleného stromu',
    'Vyškov',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    49.2785,
    16.9981,
    'https://www.uzelenehostromu-vyskov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura-blansko',
    'Restaurace U Kocoura',
    'Blansko',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru Blanska.',
    49.3629,
    16.6439,
    'https://www.ukocoura-blansko.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-blansko',
    'Restaurace Blansko',
    'Blansko',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní.',
    49.3633,
    16.6435,
    'https://www.blansko-hotel.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-medvěda',
    'Pivnice U Medvěda',
    'Blansko',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českým pivem.',
    49.3637,
    16.6431,
    'https://www.umedveda-blansko.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-rychtě-blansko',
    'Restaurace Na rychtě',
    'Blansko',
    '🌿 PURE',
    'česká kuchyně',
    'Rodinná restaurace s tradičními recepty.',
    49.3625,
    16.6443,
    'https://www.narychte-blansko.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-boskovice',
    'Restaurace U Radnice',
    'Boskovice',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na náměstí, česká klasika.',
    49.4877,
    16.6600,
    'https://www.uradnice-boskovice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura-boskovice',
    'Restaurace U Kocoura',
    'Boskovice',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    49.4881,
    16.6596,
    'https://www.ukocoura-boskovice.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 51-60
  (
    'pivnice-u-veselých',
    'Pivnice U Veselých',
    'Boskovice',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    49.4885,
    16.6592,
    'https://www.uveselych-boskovice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-panský-dům',
    'Restaurace Panský dům',
    'Boskovice',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní.',
    49.4873,
    16.6604,
    'https://www.panskydum.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura-kyjov',
    'Restaurace U Kocoura',
    'Kyjov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Kyjova.',
    49.0133,
    17.1225,
    'https://www.ukocoura-kyjov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-u-rady-kyjov',
    'Vinárna U Rady',
    'Kyjov',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna s moravskými víny a regionální kuchyní.',
    49.0137,
    17.1221,
    'https://www.urady-kyjov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-kyjov',
    'Restaurace U Radnice',
    'Kyjov',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace na náměstí, česká klasika.',
    49.0141,
    17.1217,
    'https://www.uradnice-kyjov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-na-náměstí-kyjov',
    'Pivnice Na náměstí',
    'Kyjov',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    49.0129,
    17.1229,
    'https://www.nanamesti-kyjov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-u-zlatého-hroznu',
    'Vinárna U Zlatého hroznu',
    'Hustopeče',
    '🌿 PURE',
    'vinařská kuchyně',
    'Tradiční vinárna v centru vinařské oblasti.',
    48.9401,
    16.7381,
    'https://www.uzlatehohroznu.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura-hustopece',
    'Restaurace U Kocoura',
    'Hustopeče',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    48.9405,
    16.7377,
    'https://www.ukocoura-hustopece.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-na-náměstí-hustopece',
    'Vinárna Na náměstí',
    'Hustopeče',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna s výběrem místních vín.',
    48.9409,
    16.7373,
    'https://www.nanamesti-hustopece.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-hotel-akát',
    'Restaurace Hotel Akát',
    'Hustopeče',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Hotelová restaurace s kvalitní kuchyní.',
    48.9397,
    16.7385,
    'https://www.akaht-hustopece.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 61-70
  (
    'restaurace-u-kocoura-slavkov',
    'Restaurace U Kocoura',
    'Slavkov u Brna',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v historickém centru.',
    49.1541,
    16.8767,
    'https://www.ukocoura-slavkov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-slavkov',
    'Restaurace U Radnice',
    'Slavkov u Brna',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace na náměstí, česká klasika.',
    49.1545,
    16.8763,
    'https://www.uradnice-slavkov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-austerlitz-slavkov',
    'Restaurace Austerlitz',
    'Slavkov u Brna',
    '🍷 LUXE',
    'moderní česká',
    'Stylová restaurace s historickou atmosférou.',
    49.1549,
    16.8759,
    'https://www.austerlitz-slavkov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-zlaté-koruny-slavkov',
    'Pivnice U Zlaté koruny',
    'Slavkov u Brna',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a dobrým pivem.',
    49.1537,
    16.8771,
    'https://www.uzlatekoruny-slavkov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-staré-poště',
    'Restaurace Na staré poště',
    'Tišnov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru Tišnova.',
    49.3487,
    16.4251,
    'https://www.nastaréposte-tisnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura-tisnov',
    'Restaurace U Kocoura',
    'Tišnov',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    49.3491,
    16.4247,
    'https://www.ukocoura-tisnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-medvěda-tisnov',
    'Pivnice U Medvěda',
    'Tišnov',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Hospoda s živou atmosférou a českým pivem.',
    49.3495,
    16.4243,
    'https://www.umedveda-tisnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zámku-moravský-krumlov',
    'Restaurace U Zámku',
    'Moravský Krumlov',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace v blízkosti zámku s Muchovým dílem.',
    49.0511,
    16.3101,
    'https://www.uzamku-mkrumlov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-pod-zámkem',
    'Vinárna Pod zámkem',
    'Moravský Krumlov',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna s moravskými víny a regionální kuchyní.',
    49.0515,
    16.3097,
    'https://www.podzamkem-mkrumlov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura-mk',
    'Restaurace U Kocoura',
    'Moravský Krumlov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru města.',
    49.0507,
    16.3105,
    'https://www.ukocoura-mkrumlov.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 71-80
  (
    'restaurace-na-špilberku',
    'Restaurace Na Špilberku',
    'Brno',
    '🍷 LUXE',
    'moderní česká',
    'Stylová restaurace na Špilberku s výhledem na město.',
    49.1939,
    16.5991,
    'https://www.naspilberku.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-villa-tugendhat',
    'Restaurace Villa Tugendhat',
    'Brno',
    '🍷 LUXE',
    'fine dining / moderní evropská',
    'Exkluzivní restaurace ve slavné funkcionalistické vile.',
    49.2071,
    16.6289,
    'https://www.villatugendhat.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-primátor',
    'Restaurace Primátor',
    'Brno',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická brněnská restaurace s českou kuchyní.',
    49.1969,
    16.6041,
    'https://www.primator-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-pod-radničí-věží',
    'Vinárna Pod radniční věží',
    'Brno',
    '🌿 PURE',
    'vinařská kuchyně',
    'Vinárna ve sklepních prostorách s moravskými víny.',
    49.1973,
    16.6037,
    'https://www.podradnicivezi.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-královny-elišky',
    'Restaurace U Královny Elišky',
    'Brno',
    '🌊 CALM',
    'česká / moravská kuchyně',
    'Historická restaurace s tradiční kuchyní.',
    49.1889,
    16.6121,
    'https://www.ukralovelnisky.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-asador',
    'Steakhouse Asador',
    'Brno',
    '🔥 DRAMA',
    'steakhouse / argentinská',
    'Prémiový steakhouse s argentinským masem.',
    49.1977,
    16.6033,
    'https://www.asador-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-měšťanská-pivnice',
    'Restaurace Měšťanská pivnice',
    'Brno',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Pivovarnická restaurace s vlastním pivem, živá atmosféra.',
    49.1885,
    16.6125,
    'https://www.mestanskapivnice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-portoriko',
    'Restaurace Portoriko',
    'Brno',
    '🌊 CALM',
    'česká / mezinárodní kuchyně',
    'Oblíbená restaurace s širokým menu.',
    49.1981,
    16.6029,
    'https://www.portoriko-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'vinárna-pod-věží-brno',
    'Vinárna Pod věží',
    'Brno',
    '🌿 PURE',
    'vinařská kuchyně',
    'Stylová vinárna s výběrem moravských vín.',
    49.1881,
    16.6129,
    'https://www.podvezi-brno.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-tří-zlatých-hvězd',
    'Restaurace U Tří zlatých hvězd',
    'Brno',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční brněnská restaurace se spolehlivou kuchyní.',
    49.1985,
    16.6025,
    'https://www.utrizlatychhvezd.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
