-- Import restaurací KARLOVARSKÝ KRAJ 1–50 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10 Karlovy Vary (lázeňské město)
  (
    'restaurant-embassy',
    'Restaurant Embassy',
    'Karlovy Vary',
    '🍷 LUXE',
    'fine dining / lázeňská',
    'Luxusní hotelová restaurace s michelinskou úrovní.',
    50.2288,
    12.8712,
    'https://www.embassy-kv.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'grandhotel-pupp-restaurant',
    'Grandhotel Pupp Restaurant',
    'Karlovy Vary',
    '🍷 LUXE',
    'fine dining / historická',
    'Legendární hotelová restaurace, ikona Karlových Varů.',
    50.2301,
    12.8845,
    'https://www.pupp.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'le-marche',
    'Le Marché',
    'Karlovy Vary',
    '🍷 LUXE',
    'fine dining / francouzská',
    'Francouzská gastronomie v lázeňském městě.',
    50.2267,
    12.8734,
    'https://www.lemarche-kv.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-promenáda',
    'Restaurace Promenáda',
    'Karlovy Vary',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru lázní.',
    50.2289,
    12.8756,
    'https://www.promenada-kv.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-karlovarská-kotelna',
    'Restaurace Karlovarská kotelna',
    'Karlovy Vary',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Pivnice s českou klasikou, místní atmosféra.',
    50.2278,
    12.8723,
    'https://www.karlovarskakotelna.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-svatého-lukáše',
    'Restaurace U Svatého Lukáše',
    'Karlovy Vary',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.2295,
    12.8745,
    'https://www.usvateho-lukase.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-imperial',
    'Restaurace Imperial',
    'Karlovy Vary',
    '🍷 LUXE',
    'mezinárodní / hotelová',
    'Luxusní hotelová restaurace s mezinárodní kuchyní.',
    50.2311,
    12.8867,
    'https://www.imperial-kv.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'becher-bar',
    'Becher Bar',
    'Karlovy Vary',
    '🌊 CALM',
    'česká / becherovka',
    'Ikonický bar věnovaný Becherovce, lehká kuchyně.',
    50.2283,
    12.8741,
    'https://www.becherbar.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-embassy-café',
    'Restaurace Embassy Café',
    'Karlovy Vary',
    '🌿 PURE',
    'healthy / mezinárodní',
    'Moderní café s zdravou kuchyní.',
    50.2292,
    12.8719,
    'https://www.embassycafe.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'charles-iv-restaurant',
    'Charles IV Restaurant',
    'Karlovy Vary',
    '🍷 LUXE',
    'fine dining / česká moderní',
    'Prémiová česká kuchyně v luxusním hotelu.',
    50.2305,
    12.8823,
    'https://www.charlesiv.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20 Karlovy Vary pokračování + Mariánské Lázně
  (
    'restaurace-dvořák',
    'Restaurace Dvořák',
    'Karlovy Vary',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v srdci lázní.',
    50.2276,
    12.8738,
    'https://www.dvorak-kv.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'hot-springs-hotel-restaurant',
    'Hot Springs Hotel Restaurant',
    'Karlovy Vary',
    '🍷 LUXE',
    'fine dining / wellness',
    'Hotelová restaurace s wellness zaměřením.',
    50.2318,
    12.8901,
    'https://www.hotsprings-kv.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-kv',
    'Pizzeria Venezia',
    'Karlovy Vary',
    '🌿 PURE',
    'italská / pizza',
    'Autentická italská pizza v lázních.',
    50.2285,
    12.8751,
    'https://www.venezia-kv.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-goethe',
    'Restaurace Goethe',
    'Karlovy Vary',
    '🌊 CALM',
    'česká / německá',
    'Restaurace s českou a německou kuchyní.',
    50.2297,
    12.8769,
    'https://www.goethe-kv.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'savoy-westend-hotel-restaurant',
    'Savoy Westend Hotel Restaurant',
    'Karlovy Vary',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Luxusní hotelová restaurace s tradicí.',
    50.2315,
    12.8878,
    'https://www.savoywestend.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'nobile-restaurant',
    'Nobile Restaurant',
    'Mariánské Lázně',
    '🍷 LUXE',
    'fine dining / mezinárodní',
    'Luxusní restaurace v lázeňském městě.',
    49.9645,
    12.7012,
    'https://www.nobile-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-kolonáda',
    'Restaurace Kolonáda',
    'Mariánské Lázně',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace u kolonády.',
    49.9658,
    12.7034,
    'https://www.kolonada-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-corso',
    'Restaurace Corso',
    'Mariánské Lázně',
    '🌊 CALM',
    'česká / mezinárodní',
    'Oblíbená restaurace v centru lázní.',
    49.9651,
    12.7023,
    'https://www.corso-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'golf-restaurant-ml',
    'Golf Restaurant',
    'Mariánské Lázně',
    '🍷 LUXE',
    'fine dining / golf',
    'Prémiová restaurace u golfového hřiště.',
    49.9723,
    12.7156,
    'https://www.golfrestaurant-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beethoven',
    'Restaurace Beethoven',
    'Mariánské Lázně',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace s klasickou českou kuchyní.',
    49.9662,
    12.7045,
    'https://www.beethoven-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-30 Mariánské Lázně pokračování + Cheb
  (
    'villa-butterfly-restaurant',
    'Villa Butterfly Restaurant',
    'Mariánské Lázně',
    '🍷 LUXE',
    'fine dining / vila',
    'Stylová restaurace ve historické vile.',
    49.9639,
    12.6989,
    'https://www.villabutterfly.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlaté-koule',
    'Restaurace U Zlaté koule',
    'Mariánské Lázně',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    49.9654,
    12.7028,
    'https://www.uzlatekoule-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-tosca',
    'Pizzeria Tosca',
    'Mariánské Lázně',
    '🌿 PURE',
    'italská / pizza',
    'Oblíbená pizzerie v lázních.',
    49.9647,
    12.7019,
    'https://www.tosca-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-crystal-palace',
    'Restaurace Crystal Palace',
    'Mariánské Lázně',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Luxusní hotelová restaurace.',
    49.9668,
    12.7067,
    'https://www.crystalpalace-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-medité',
    'Restaurace Medité',
    'Mariánské Lázně',
    '🌿 PURE',
    'healthy / lázeňská',
    'Zdravá kuchyně pro lázeňské hosty.',
    49.9641,
    12.7001,
    'https://www.medite-ml.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-valdštejnská-lodžie',
    'Restaurace Valdštejnská lodžie',
    'Cheb',
    '🌊 CALM',
    'česká kuchyně',
    'Historická restaurace v centru Chebu.',
    50.0796,
    12.3712,
    'https://www.valdstejnskalodzie.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-špalíček',
    'Restaurace Špalíček',
    'Cheb',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v historických domech Špalíček.',
    50.0801,
    12.3723,
    'https://www.spalicek-cheb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlatého-koně',
    'Restaurace U Zlatého koně',
    'Cheb',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru města.',
    50.0789,
    12.3701,
    'https://www.uzlateho-kone.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'gaststätte-röslein',
    'Gaststätte Röslein',
    'Cheb',
    '🌊 CALM',
    'česká / německá',
    'Restaurace s českou a německou kuchyní.',
    50.0793,
    12.3718,
    'https://www.roslein-cheb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-gargano',
    'Pizzeria Gargano',
    'Cheb',
    '🌿 PURE',
    'italská / pizza',
    'Oblíbená italská pizzerie v Chebu.',
    50.0785,
    12.3694,
    'https://www.gargano-cheb.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 31-40 Cheb pokračování + Sokolov
  (
    'restaurace-kavárna-monarch',
    'Restaurace Kavárna Monarch',
    'Cheb',
    '🌊 CALM',
    'česká / kavárna',
    'Kavárna s restaurací v centru Chebu.',
    50.0798,
    12.3715,
    'https://www.monarch-cheb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'hospůdka-u-tří-sedláků',
    'Hospůdka U Tří sedláků',
    'Cheb',
    '🌮 CHAOS',
    'česká kuchyně / hospoda',
    'Tradiční hospoda s českou klasikou.',
    50.0791,
    12.3707,
    'https://www.utrisedlaku.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'barbarossa-restaurant',
    'Barbarossa Restaurant',
    'Cheb',
    '🌊 CALM',
    'mezinárodní',
    'Stylová restaurace s mezinárodní kuchyní.',
    50.0804,
    12.3734,
    'https://www.barbarossa-cheb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-čápa',
    'Restaurace U Čápa',
    'Cheb',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.0787,
    12.3698,
    'https://www.ucapa-cheb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-montana',
    'Steakhouse Montana',
    'Cheb',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v centru Chebu.',
    50.0795,
    12.3721,
    'https://www.montana-cheb.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slávie',
    'Restaurace Slávie',
    'Sokolov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Sokolově.',
    50.1812,
    12.6401,
    'https://www.slavie-sokolov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-holuba',
    'Pivnice U Holuba',
    'Sokolov',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice s českou klasikou.',
    50.1823,
    12.6423,
    'https://www.uholuba-sokolov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-výsluní',
    'Restaurace Na Výsluní',
    'Sokolov',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace s českou klasikou.',
    50.1818,
    12.6412,
    'https://www.navysluni-sokolov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-sokolov',
    'Pizzeria Venezia',
    'Sokolov',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Sokolově.',
    50.1828,
    12.6434,
    'https://www.venezia-sokolov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-sport',
    'Restaurace Sport',
    'Sokolov',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace u sportoviště.',
    50.1815,
    12.6395,
    'https://www.sport-sokolov.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 41-50 Menší města (Ostrov, Aš, Kraslice, Horní Slavkov)
  (
    'restaurace-u-dvou-kohoutů',
    'Restaurace U Dvou kohoutů',
    'Ostrov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Ostrově.',
    50.3067,
    12.9389,
    'https://www.udvoukouhoutu-ostrov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-capri',
    'Pizzeria Capri',
    'Ostrov',
    '🌿 PURE',
    'italská / pizza',
    'Oblíbená pizzerie v Ostrově.',
    50.3079,
    12.9412,
    'https://www.capri-ostrov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-černý-orel',
    'Restaurace Černý orel',
    'Ostrov',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.3072,
    12.9398,
    'https://www.cernyorel-ostrov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-aš',
    'Restaurace Aš',
    'Aš',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Aši.',
    50.2234,
    12.1945,
    'https://www.restaurace-as.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'hospůdka-u-zámku',
    'Hospůdka U Zámku',
    'Aš',
    '🌮 CHAOS',
    'česká kuchyně / hospoda',
    'Pivnice u zámku v Aši.',
    50.2241,
    12.1956,
    'https://www.uzamku-as.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-kraslice',
    'Restaurace Kraslice',
    'Kraslice',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v Kraslicích.',
    50.3245,
    12.5156,
    'https://www.restaurace-kraslice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-bellini',
    'Pizzeria Bellini',
    'Kraslice',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Kraslicích.',
    50.3252,
    12.5167,
    'https://www.bellini-kraslice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavkov',
    'Restaurace Slavkov',
    'Horní Slavkov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Horním Slavkově.',
    50.1289,
    12.7934,
    'https://www.slavkov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-radnice',
    'Pivnice U Radnice',
    'Horní Slavkov',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice u náměstí.',
    50.1295,
    12.7945,
    'https://www.uradnice-hslavkov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-na-náměstí',
    'Restaurace Na Náměstí',
    'Horní Slavkov',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace na náměstí.',
    50.1292,
    12.7939,
    'https://www.nanamesti-hslavkov.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
