-- Import restaurací KRÁLOVÉHRADECKÝ KRAJ 1–60 do GURMAO.cz (KOMPLETNÍ)
-- Zkopíruj tento SQL do Supabase → SQL Editor → New query → Run

INSERT INTO restaurants (
  slug, 
  name, 
  city, 
  vibe, 
  tag, 
  description, 
  latitude, 
  longitude, 
  image_url,
  created_at
) VALUES 
  -- 1-10 Hradec Králové (krajské město)
  (
    'restaurant-saloon',
    'Restaurant Saloon',
    'Hradec Králové',
    '🍷 LUXE',
    'fine dining / steakhouse',
    'Nejlepší fine dining v Hradci, prémiové steaky.',
    50.2094,
    15.8323,
    'https://www.saloon-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice',
    'Restaurace U Radnice',
    'Hradec Králové',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace na Velkém náměstí.',
    50.2101,
    15.8334,
    'https://www.uradnice-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivovar-konrad',
    'Pivovar Konrad',
    'Hradec Králové',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Minipivovar s vlastním pivem a českou klasikou.',
    50.2108,
    15.8345,
    'https://www.konrad-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-nová-adalbertinum',
    'Restaurace Nová Adalbertinum',
    'Hradec Králové',
    '🍷 LUXE',
    'fine dining / moderní česká',
    'Luxusní restaurace s moderní českou kuchyní.',
    50.2097,
    15.8328,
    'https://www.adalbertinum.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-grosseto',
    'Pizzeria Grosseto',
    'Hradec Králové',
    '🌿 PURE',
    'italská / pizza',
    'Autentická italská pizza z pece.',
    50.2115,
    15.8356,
    'https://www.grosseto-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-královny-elišky',
    'Restaurace U Královny Elišky',
    'Hradec Králové',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace v centru města.',
    50.2104,
    15.8339,
    'https://www.ukralovnyelisky.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-rango',
    'Steakhouse Rango',
    'Hradec Králové',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v Hradci Králové.',
    50.2118,
    15.8362,
    'https://www.rango-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-semináře',
    'Restaurace U Semináře',
    'Hradec Králové',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace s českou klasikou.',
    50.2092,
    15.8318,
    'https://www.useminare.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'sushi-bar-fuji',
    'Sushi Bar Fuji',
    'Hradec Králové',
    '🌿 PURE',
    'asijská / sushi',
    'Čerstvé sushi v Hradci Králové.',
    50.2111,
    15.8351,
    'https://www.fuji-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-51',
    'Kavárna 51',
    'Hradec Králové',
    '🌊 CALM',
    'kavárna / dezerty',
    'Moderní kavárna s vynikajícími dezerty.',
    50.2099,
    15.8330,
    'https://www.kavarna51.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 11-20 Hradec Králové pokračování
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Hradec Králové',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.2105,
    15.8340,
    'https://www.ukata-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-station',
    'Burger Station',
    'Hradec Králové',
    '🔥 DRAMA',
    'burger / fast casual',
    'Oblíbený burger bar v Hradci.',
    50.2114,
    15.8354,
    'https://www.burgerstation-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda',
    'Restaurace Beseda',
    'Hradec Králové',
    '🌊 CALM',
    'česká / mezinárodní',
    'Restaurace v historické budově Besedy.',
    50.2096,
    15.8326,
    'https://www.beseda-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-semika',
    'Pivnice U Semíka',
    'Hradec Králové',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Pivnice s českou klasikou.',
    50.2107,
    15.8343,
    'https://www.usemika.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia',
    'Restaurace Slavia',
    'Hradec Králové',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.2102,
    15.8336,
    'https://www.slavia-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurant-imperial',
    'Restaurant Imperial',
    'Hradec Králové',
    '🍷 LUXE',
    'fine dining / hotelová',
    'Luxusní hotelová restaurace.',
    50.2095,
    15.8324,
    'https://www.imperial-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia',
    'Pizzeria Venezia',
    'Hradec Králové',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Hradci.',
    50.2109,
    15.8347,
    'https://www.venezia-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura',
    'Restaurace U Kocoura',
    'Hradec Králové',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v centru.',
    50.2103,
    15.8338,
    'https://www.ukocoura-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-restaurant-hong-kong',
    'Asia Restaurant Hong Kong',
    'Hradec Králové',
    '🌿 PURE',
    'asijská / čínská',
    'Asijská kuchyně v Hradci Králové.',
    50.2112,
    15.8353,
    'https://www.hongkong-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-tří-koček',
    'Restaurace U Tří koček',
    'Hradec Králové',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.2098,
    15.8329,
    'https://www.utrikotek-hk.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 21-30 Trutnov
  (
    'restaurace-u-bílého-koně',
    'Restaurace U Bílého koně',
    'Trutnov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Trutnově.',
    50.5608,
    15.9123,
    'https://www.ubilehokone-trutnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivovar-krakonoš',
    'Pivovar Krakonoš',
    'Trutnov',
    '🌮 CHAOS',
    'česká kuchyně / pivovar',
    'Minipivovar s vlastním pivem.',
    50.5619,
    15.9145,
    'https://www.krakonos.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-roma',
    'Pizzeria Roma',
    'Trutnov',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Trutnově.',
    50.5614,
    15.9134,
    'https://www.roma-trutnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia',
    'Restaurace Slavia',
    'Trutnov',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.5625,
    15.9156,
    'https://www.slavia-trutnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-montana',
    'Steakhouse Montana',
    'Trutnov',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v Trutnově.',
    50.5617,
    15.9140,
    'https://www.montana-trutnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Trutnov',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru.',
    50.5611,
    15.9128,
    'https://www.ukata-trutnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-adršpach',
    'Restaurace Adršpach',
    'Adršpach',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace u skalního města.',
    50.6123,
    16.1145,
    'https://www.restaurace-adrspach.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-penzion-skalní-město',
    'Restaurace Penzion Skalní město',
    'Adršpach',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace u Adršpašských skal.',
    50.6134,
    16.1167,
    'https://www.skalnimesto.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-horní-malá-úpa',
    'Restaurace Horní Malá Úpa',
    'Malá Úpa',
    '🌊 CALM',
    'česká kuchyně',
    'Horská restaurace v Malé Úpě.',
    50.7234,
    15.8678,
    'https://www.malaupa.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-pec-pod-sněžkou',
    'Restaurace Pec pod Sněžkou',
    'Pec pod Sněžkou',
    '🌊 CALM',
    'česká kuchyně',
    'Restaurace v lyžařském středisku.',
    50.6912,
    15.7389,
    'https://www.pecpodsnezkou.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 31-40 Náchod, Jaroměř
  (
    'restaurace-u-beránka',
    'Restaurace U Beránka',
    'Náchod',
    '🍷 LUXE',
    'fine dining / česká moderní',
    'Nejlepší restaurace v Náchodě.',
    50.4167,
    16.1634,
    'https://www.uberanka.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kocoura',
    'Restaurace U Kocoura',
    'Náchod',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Náchodě.',
    50.4178,
    16.1656,
    'https://www.ukocoura-nachod.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-nachod',
    'Pizzeria Venezia',
    'Náchod',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Náchodě.',
    50.4173,
    16.1645,
    'https://www.venezia-nachod.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-jeleníka',
    'Pivnice U Jeleníka',
    'Náchod',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice v Náchodě.',
    50.4184,
    16.1667,
    'https://www.ujelenika.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia',
    'Restaurace Slavia',
    'Náchod',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.4170,
    16.1639,
    'https://www.slavia-nachod.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-radnice-jaromer',
    'Restaurace U Radnice',
    'Jaroměř',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Jaroměři.',
    50.3556,
    15.9212,
    'https://www.uradnice-jaromer.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-bella',
    'Pizzeria Bella',
    'Jaroměř',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Jaroměři.',
    50.3567,
    15.9234,
    'https://www.bella-jaromer.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-zlatého-lva',
    'Restaurace U Zlatého lva',
    'Jaroměř',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční česká restaurace.',
    50.3561,
    15.9223,
    'https://www.uzlateho-lva-jaromer.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-rytíře',
    'Pivnice U Rytíře',
    'Jaroměř',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice v Jaroměři.',
    50.3573,
    15.9245,
    'https://www.urytire.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-beseda-jaromer',
    'Restaurace Beseda',
    'Jaroměř',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická restaurace v Jaroměři.',
    50.3564,
    15.9228,
    'https://www.beseda-jaromer.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 41-50 Jičín
  (
    'restaurace-u-černého-koně',
    'Restaurace U Černého koně',
    'Jičín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Jičíně.',
    50.4373,
    15.3512,
    'https://www.ucernehokone-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-valdštejnská-lodžie',
    'Restaurace Valdštejnská lodžie',
    'Jičín',
    '🍷 LUXE',
    'fine dining / historická',
    'Luxusní restaurace v historické budově.',
    50.4384,
    15.3534,
    'https://www.valdstejnskalodzie-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-sicilia',
    'Pizzeria Sicilia',
    'Jičín',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Jičíně.',
    50.4378,
    15.3523,
    'https://www.sicilia-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pivnice-u-kocoura',
    'Pivnice U Kocoura',
    'Jičín',
    '🌮 CHAOS',
    'česká kuchyně / pivnice',
    'Oblíbená pivnice v Jičíně.',
    50.4389,
    15.3545,
    'https://www.ukocoura-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-slavia',
    'Restaurace Slavia',
    'Jičín',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace.',
    50.4375,
    15.3518,
    'https://www.slavia-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'steakhouse-dakota',
    'Steakhouse Dakota',
    'Jičín',
    '🔥 DRAMA',
    'steakhouse / grill',
    'Kvalitní steaky v Jičíně.',
    50.4381,
    15.3529,
    'https://www.dakota-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-u-kata',
    'Restaurace U Kata',
    'Jičín',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v centru.',
    50.4376,
    15.3520,
    'https://www.ukata-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'asia-bistro-jicin',
    'Asia Bistro',
    'Jičín',
    '🌿 PURE',
    'asijská / čínská',
    'Asijská kuchyně v Jičíně.',
    50.4385,
    15.3538,
    'https://www.asiabistro-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'kavárna-retro',
    'Kavárna Retro',
    'Jičín',
    '🌊 CALM',
    'kavárna / dezerty',
    'Retro kavárna s domácími dezerty.',
    50.4379,
    15.3526,
    'https://www.retro-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'burger-factory-jicin',
    'Burger Factory',
    'Jičín',
    '🔥 DRAMA',
    'burger / fast casual',
    'Oblíbený burger bar.',
    50.4382,
    15.3531,
    'https://www.burgerfactory-jicin.cz/images/restaurace.jpg',
    NOW()
  ),
  -- 51-60 Menší města
  (
    'restaurace-dvůr-králové',
    'Restaurace Dvůr Králové',
    'Dvůr Králové nad Labem',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace ve Dvoře Králové.',
    50.4312,
    15.8145,
    'https://www.restaurace-dk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-venezia-dk',
    'Pizzeria Venezia',
    'Dvůr Králové nad Labem',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie ve Dvoře Králové.',
    50.4323,
    15.8167,
    'https://www.venezia-dk.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-nové-město',
    'Restaurace Nové Město',
    'Nové Město nad Metují',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Novém Městě.',
    50.3445,
    16.1512,
    'https://www.restaurace-nm.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-dobruška',
    'Restaurace Dobruška',
    'Dobruška',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace v Dobrušce.',
    50.2934,
    16.1623,
    'https://www.restaurace-dobruska.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-napoli-dobruska',
    'Pizzeria Napoli',
    'Dobruška',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Dobrušce.',
    50.2945,
    16.1645,
    'https://www.napoli-dobruska.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-rychnov',
    'Restaurace Rychnov',
    'Rychnov nad Kněžnou',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Rychnově.',
    50.1623,
    16.2745,
    'https://www.restaurace-rychnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'pizzeria-roma-rychnov',
    'Pizzeria Roma',
    'Rychnov nad Kněžnou',
    '🌿 PURE',
    'italská / pizza',
    'Italská pizzerie v Rychnově.',
    50.1634,
    16.2767,
    'https://www.roma-rychnov.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-hořice',
    'Restaurace Hořice',
    'Hořice',
    '🌊 CALM',
    'česká kuchyně',
    'Klasická česká restaurace v Hořicích.',
    50.3678,
    15.6334,
    'https://www.restaurace-horice.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-kostelec',
    'Restaurace Kostelec',
    'Kostelec nad Orlicí',
    '🌊 CALM',
    'česká kuchyně',
    'Tradiční restaurace v Kostelci.',
    50.1234,
    16.2123,
    'https://www.restaurace-kostelec.cz/images/restaurace.jpg',
    NOW()
  ),
  (
    'restaurace-červený-kostelec',
    'Restaurace Červený Kostelec',
    'Červený Kostelec',
    '🌊 CALM',
    'česká kuchyně',
    'Oblíbená restaurace v Červeném Kostelci.',
    50.4756,
    16.0912,
    'https://www.restaurace-ck.cz/images/restaurace.jpg',
    NOW()
  )
ON CONFLICT (slug) DO NOTHING;
