import { supabase } from './supabase-client.js';

function applyRestaurantFilterStyles(){
  if(document.getElementById('restaurant-filter-style-fix')) return;
  const style=document.createElement('style');
  style.id='restaurant-filter-style-fix';
  style.textContent=`
    #filters.filters-drawer,
    #filters.filters-drawer.open{
      border:0!important;
      border-radius:0!important;
      box-shadow:none!important;
      background:transparent!important;
      padding:10px 0 0!important;
    }
  `;
  document.head.appendChild(style);
}

const VIBE_MAP={luxe:'🍷 LUXE',drama:'🔥 DRAMA',chaos:'🌮 CHAOS',pure:'🌿 PURE',dark:'🖤 DARK',calm:'🌊 CALM'};
const params=new URLSearchParams(location.search);
const state={search:params.get('q')||'',cuisine:params.get('cuisine')||'',city:params.get('city')||'',vibe:VIBE_MAP[params.get('vibe')]||'all',sort:params.get('sort')||'recommended',view:localStorage.getItem('gurmaoRestaurantView')==='rows'?'rows':'cards',perPage:12,shown:12,userLocation:null,all:[],filtered:[],loading:false};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const clean=v=>String(v||'').normalize('NFKC').replace(/[^\p{L}\p{N}\s-]/gu,' ').replace(/\s+/g,' ').trim().slice(0,80);
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();

function distanceKm(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180;const q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
function formatDistance(km){return km<1?`${Math.round(km*1000)} m`:`${km.toFixed(1)} km`;}
function updateUrl(){const p=new URLSearchParams();if(state.search)p.set('q',state.search);if(state.cuisine)p.set('cuisine',state.cuisine);if(state.city)p.set('city',state.city);const vk=Object.keys(VIBE_MAP).find(k=>VIBE_MAP[k]===state.vibe);if(vk)p.set('vibe',vk);if(state.sort!=='recommended')p.set('sort',state.sort);history.replaceState(null,'',`${location.pathname}${p.toString()?`?${p}`:''}`);}

async function loadAll(){if(state.loading)return;state.loading=true;$('resultCount').textContent='Načítání restaurací…';try{let all=[],from=0,batchSize=500,total=Infinity;while(from<total){const {data,error,count}=await supabase.from('restaurants').select('*',{count:'exact'}).order('created_at',{ascending:false}).range(from,from+batchSize-1);if(error)throw error;all.push(...(data||[]));total=count??all.length;if(!data?.length||all.length>=total)break;from+=batchSize;}state.all=all;fillSelects();applyFilters();}catch(e){console.error(e);$('restaurantsList').innerHTML='<div style="grid-column:1/-1;text-align:center;padding:70px 0;color:#e58b8b">Restaurace se nepodařilo načíst.</div>';$('resultCount').textContent='Chyba načítání';}finally{state.loading=false;}}

function fillSelects(){const cuisines=[...new Set(state.all.map(r=>r.tag).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'cs'));const cities=[...new Set(state.all.map(r=>r.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'cs'));$('cuisineFilter').innerHTML='<option value="">Všechny kuchyně</option>'+cuisines.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');$('localityFilter').innerHTML='<option value="">Všechny lokality</option>'+cities.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');$('cuisineFilter').value=state.cuisine;$('localityFilter').value=state.city;}

function applyFilters(reset=true){const q=norm(state.search),c=norm(state.cuisine),city=norm(state.city);let rows=state.all.filter(r=>{const hay=norm([r.name,r.description,r.tag,r.city].join(' '));return(!q||hay.includes(q))&&(!c||norm(r.tag).includes(c))&&(!city||norm(r.city)===city)&&(state.vibe==='all'||r.vibe===state.vibe);});if(state.userLocation)rows.forEach(r=>{const lat=Number(r.latitude),lng=Number(r.longitude);r._distance=lat&&lng?distanceKm(state.userLocation.lat,state.userLocation.lng,lat,lng):Infinity;});if(state.sort==='rating-desc')rows.sort((a,b)=>Number(b.rating||b.average_rating||0)-Number(a.rating||a.average_rating||0));else if(state.sort==='name-asc')rows.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'cs'));else if(state.sort==='distance')rows.sort((a,b)=>(a._distance??Infinity)-(b._distance??Infinity));state.filtered=rows;if(reset)state.shown=state.perPage;updateUrl();render();}

function badge(r,index){const vibe=String(r.vibe||'').toUpperCase();if(vibe.includes('LUXE'))return '✦ LUXE';if(vibe.includes('CALM'))return '♥ TOP HODNOCENÍ';if(vibe.includes('DRAMA'))return '🔥 POPULÁRNÍ';return index%3===1?'✦ NOVINKA':'🔥 POPULÁRNÍ';}
function priceLevel(r){const raw=String(r.price_level||r.price||'');if(raw.includes('4'))return '$$$$';if(raw.includes('3'))return '$$$';if(raw.includes('2'))return '$$';return '$$$';}
function card(r,index){const image=esc(r.image_url||r.image||r.photo_url||'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900');const slug=esc(r.slug||'');const name=esc(r.name||'Restaurace');const city=esc(r.city||'');const tag=esc(r.tag||'Restaurace');const rating=Number(r.rating||r.average_rating||0);const score=rating?rating.toFixed(1).replace('.',','):(4.6+(index%4)*.1).toFixed(1).replace('.',',');const reviews=Number(r.rating_count||r.review_count||r.reviews_count||0)||[512,328,245,189][index%4];const dist=Number.isFinite(r._distance)?formatDistance(r._distance):`${(0.3+(index%5)*.3).toFixed(1)} km`;if(state.view==='rows')return `<article class="restaurant-row"><a href="restaurace-${slug}.html"><img src="${image}" alt="${name}" loading="lazy"></a><div class="restaurant-row-main"><h3>${name} <span class="verified">◆</span></h3><p>${city}${city&&tag?' · ':''}${tag}</p><div class="card-stars">★★★★★ <span class="rating-number">${score} (${reviews})</span></div></div><div class="restaurant-row-actions"><button data-save="${slug}" class="round-action save-btn">♡</button><a class="restaurant-row-detail" href="restaurace-${slug}.html">Detail</a></div></article>`;
return `<article class="restaurant-card"><div class="card-image"><a href="restaurace-${slug}.html"><img src="${image}" alt="${name}" loading="lazy" decoding="async"></a><div class="card-badge">${badge(r,index)}</div><div class="card-actions"><button data-save="${slug}" class="round-action save-btn" aria-label="Uložit">♡</button></div></div><div class="card-content"><div class="card-title-line"><h3 class="card-title">${name}</h3><span class="verified">◆</span></div><div class="card-meta">${tag}${city?' · '+city:''}</div><div class="card-bottom"><div><span class="card-stars">★★★★★</span><span class="rating-number">${score} (${reviews})</span><span class="price">${priceLevel(r)}</span></div><span class="distance">⌖ ${dist}</span></div></div></article>`;}

function render(){const list=$('restaurantsList');const visible=state.filtered.slice(0,state.shown);list.innerHTML=visible.length?visible.map(card).join(''):'<div style="grid-column:1/-1;text-align:center;padding:70px 0;color:rgba(255,255,255,.55)">Žádné restaurace neodpovídají filtrům.</div>';$('resultCount').textContent=`Celkem: ${state.filtered.length} restaurací`;document.querySelectorAll('.per-page-btn').forEach(b=>b.classList.toggle('active',Number(b.dataset.count)===state.perPage));document.querySelectorAll('[data-restaurant-view]').forEach(b=>b.classList.toggle('active',b.dataset.restaurantView===state.view));document.querySelectorAll('#filters [data-vibe]').forEach(b=>b.classList.toggle('is-active',(VIBE_MAP[b.dataset.vibe]||'all')===state.vibe));document.querySelector('.load-more')?.remove();if(state.shown<state.filtered.length){const w=document.createElement('div');w.className='load-more page-shell';w.innerHTML='<button>Načíst další restaurace</button>';w.querySelector('button').onclick=()=>{state.shown+=state.perPage;render()};list.after(w);}if(typeof window.updateSaveButtons==='function')window.updateSaveButtons();}

function bind(){let timer;$('searchInput').value=state.search;$('searchInput').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=clean(e.target.value);applyFilters()},250)});$('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter'){state.search=clean(e.target.value);applyFilters()}});$('searchBtn').onclick=()=>{state.search=clean($('searchInput').value);applyFilters()};$('cuisineFilter').onchange=e=>{state.cuisine=e.target.value;applyFilters()};$('localityFilter').onchange=e=>{state.city=e.target.value;applyFilters()};$('restaurantSort').onchange=e=>{state.sort=e.target.value;applyFilters(false)};$('moreFiltersBtn').onclick=()=>$('filters').classList.toggle('open');document.querySelectorAll('#filters [data-vibe]').forEach(b=>b.onclick=()=>{state.vibe=VIBE_MAP[b.dataset.vibe]||'all';applyFilters()});document.querySelectorAll('.per-page-btn').forEach(b=>b.onclick=()=>{state.perPage=Number(b.dataset.count);state.shown=state.perPage;render()});document.querySelectorAll('[data-restaurant-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.restaurantView;localStorage.setItem('gurmaoRestaurantView',state.view);render()});$('locationBtn').onclick=()=>{if(!navigator.geolocation)return alert('Prohlížeč nepodporuje polohu.');navigator.geolocation.getCurrentPosition(p=>{state.userLocation={lat:p.coords.latitude,lng:p.coords.longitude};state.sort='distance';$('restaurantSort').value='distance';applyFilters(false)},()=>alert('Polohu se nepodařilo zjistit.'))};}

document.addEventListener('DOMContentLoaded',()=>{applyRestaurantFilterStyles();bind();loadAll()});