import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const DAYS=['sun','mon','tue','wed','thu','fri','sat'];
function errorMessage(error:unknown){if(error instanceof Error)return error.message;if(typeof error==='string')return error;if(error&&typeof error==='object'){const v=error as Record<string,unknown>;const p=[v.message,v.details,v.hint,v.code].filter(Boolean).map(String);if(p.length)return p.join(' | ');try{return JSON.stringify(error)}catch{return'Neznámá objektová chyba'}}return String(error||'Neznámá chyba')}
function timeValue(value:unknown){if(!value||typeof value!=='object')return null;const i=value as {hour?:number;minute?:number};if(!Number.isInteger(i.hour)||i.hour!<0||i.hour!>23)return null;const m=Number.isInteger(i.minute)?i.minute!:0;if(m<0||m>59)return null;return `${String(i.hour).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function normalizePeriods(periods:unknown){const out:Record<string,string>={mon:'closed',tue:'closed',wed:'closed',thu:'closed',fri:'closed',sat:'closed',sun:'closed'};const temp:Record<string,string[]>={mon:[],tue:[],wed:[],thu:[],fri:[],sat:[],sun:[]};if(!Array.isArray(periods))return out;for(const p of periods){const d=Number(p?.open?.day),o=timeValue(p?.open),c=timeValue(p?.close);if(!Number.isInteger(d)||d<0||d>6||!o)continue;temp[DAYS[d]].push(`${o}-${c||'24:00'}`)}for(const k of Object.keys(temp))if(temp[k].length)out[k]=temp[k].join(', ');return out}
async function googleJson(url:string,apiKey:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{'Content-Type':'application/json','X-Goog-Api-Key':apiKey,...(init.headers||{})}});if(!r.ok){const t=await r.text();let d=t;try{const p=JSON.parse(t);d=p?.error?.message||p?.message||t}catch{}throw new Error(`Google Places ${r.status}: ${d}`)}return r.json()}
async function findPlace(r:any,k:string){if(r.google_place_id)return r.google_place_id;const textQuery=[r.name,r.address,r.city,'Česko'].filter(Boolean).join(', ');const d=await googleJson('https://places.googleapis.com/v1/places:searchText',k,{method:'POST',headers:{'X-Goog-FieldMask':'places.id,places.displayName,places.formattedAddress'},body:JSON.stringify({textQuery,languageCode:'cs',regionCode:'CZ',maxResultCount:1})});return d?.places?.[0]?.id||null}
async function loadHours(id:string,k:string){return googleJson(`https://places.googleapis.com/v1/places/${encodeURIComponent(id)}?languageCode=cs`,k,{headers:{'X-Goog-FieldMask':'id,regularOpeningHours,currentOpeningHours'}})}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{const u=Deno.env.get('SUPABASE_URL')!,a=Deno.env.get('SUPABASE_ANON_KEY')!,s=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,g=Deno.env.get('GOOGLE_PLACES_API_KEY');if(!g)throw new Error('Chybí secret GOOGLE_PLACES_API_KEY.');const h=req.headers.get('Authorization')||'';const uc=createClient(u,a,{global:{headers:{Authorization:h}}});const {data:{user},error:ue}=await uc.auth.getUser();if(ue||!user||user.app_metadata?.role!=='admin')return new Response(JSON.stringify({error:'Pouze administrátor.'}),{status:403,headers:{...corsHeaders,'Content-Type':'application/json'}});const b=await req.json().catch(()=>({})),limit=Math.min(Math.max(Number(b.limit)||10,1),25),rid=b.restaurant_id?String(b.restaurant_id):null,refresh=Boolean(b.refresh_all),service=createClient(u,s);let q=service.from('restaurants').select('id,name,address,city,google_place_id,opening_hours_verified_at').order('opening_hours_verified_at',{ascending:true,nullsFirst:true}).limit(limit);if(rid)q=q.eq('id',rid);else if(!refresh)q=q.is('opening_hours_verified_at',null);const {data:rows,error}=await q;if(error)throw error;const results=[];for(const r of rows||[]){try{const id=await findPlace(r,g);if(!id){results.push({id:r.id,name:r.name,status:'not_found'});continue}const p=await loadHours(id,g),periods=p?.regularOpeningHours?.periods||p?.currentOpeningHours?.periods||[],opening_hours=normalizePeriods(periods);const {error:e}=await service.from('restaurants').update({google_place_id:id,opening_hours,opening_hours_source:'google',opening_hours_verified_at:new Date().toISOString()}).eq('id',r.id);if(e)throw e;results.push({id:r.id,name:r.name,status:periods.length?'updated':'no_hours',place_id:id})}catch(e){results.push({id:r.id,name:r.name,status:'error',error:errorMessage(e)})}}return new Response(JSON.stringify({processed:results.length,results}),{headers:{...corsHeaders,'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:errorMessage(e)}),{status:500,headers:{...corsHeaders,'Content-Type':'application/json'}})}});