create table if not exists public.daily_menus (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  menu_date date not null,
  source_url text not null,
  source_type text not null default 'website',
  menu_text text not null,
  content_hash text not null,
  fetched_at timestamptz not null default now(),
  status text not null default 'published' check (status in ('published','review','error')),
  unique (restaurant_id, menu_date)
);

create index if not exists daily_menus_restaurant_date_idx
  on public.daily_menus (restaurant_id, menu_date desc);

alter table public.daily_menus enable row level security;

drop policy if exists "Daily menus are publicly readable" on public.daily_menus;
create policy "Daily menus are publicly readable"
  on public.daily_menus for select
  using (status = 'published');

comment on table public.daily_menus is 'Automaticky získaná denní menu restaurací.';
